### ISSUE TITLE
Config factory typo in docs

### ISSUE THREAD

**Issue by chris2039** [zendframework/zend-expressive#104]
Looks like there is a quick typo in /doc/book/usage-examples.md where the config globbing examples are.  The example uses \Zend\Config\Config::fromFiles() but it appears that method is actually in the factory class - \Zend\Config\Factory::fromFiles().  Cheers!

**Comment by weierophinney** [comment]
Oops! Care to create a pull request?

**Comment by chris2039** [comment]
Sure, just sent the request.
