### ISSUE TITLE
Renaming route to router?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#119]
Hi !

While reading some part of the source code, I've felt a bit confused by the naming of the various router adapters.

Actually, it seems that the various adapters are actually router (a list of route, and can be matched), but all the adapter are actually named "AuraRoutE", "FastRoutE", "Zf2RoutE". That's a bit confusing because in my head, a route is... well, a single route.

I'd suggest therefore renaming:

* AuraRoute => AuraRouter
* FastRoute => FastRouter
* Zf2 => Zf2Router (for consistency)

I know a version has already been tagged, but I think this would be a sane change to reduce confusness (and I really was ^^).

**Comment by weierophinney** [comment]
The naming is a result of FastRoute, as that was the first we implemented,
and that's the package name.

I think a name change would be fine; the tag was in the 0.* series, after
all, so API changes are still allowed.

Want to create a PR?

If so, we should also standardize template implementation names.

**Comment by bakura10** [comment]
Yep. I will do that tomorrow. What about FastRouteRouter ? This way we stay entirely consistent.

Envoyé de mon iPhone

**Comment by weierophinney** [comment]
Fixed with #120.
