### ISSUE TITLE
404 status seems not setted by default if we are using middleware_pipeline

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive#135]
If we add middleware_pipelines for pre_routing and/or post_routing, the 404 status doesn't filled by default, I need to $router->match($request)->isFailure() check and set $response->withStatus(404); manually

**Comment by weierophinney** [comment]
I'm using middleware_pipeline on mwop.net, and successfully getting 404s
(moreover, they're even templated, via the templated error handler). Take a
look at the configuration on my site (
https://github.com/weierophinney/mwop.net), and see if you can see any
meaningful differences; if not, I'll have you post your configuration for
me to examine.

**Comment by samsonasik** [comment]
I'm using https://github.com/xtreamwayz/expressive-composer-installer by @xtreamwayz ( not sure if related with that ), and my configuration posted as blog yesterday: https://samsonasik.wordpress.com/2015/09/20/zendexpressive-on-callable-next-and-middleware-pipeline/ , on `SugarAction` middleware, I add note for that. Please let me know if missing something

**Comment by xtreamwayz** [comment]
I just tried this class as a pre_routing middleware:

```php
<?php

namespace App\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class NotFoundTest
{
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {
        return $next($request, $response->withStatus(404), 'Not found test');
    }
}
```

I do get a templated error page, but I get the 500 internal error page. The correct 404 header status code is set. And when displaying the error object I get the right one.

So I guess if there is anything wrong, then it would be that expressive doesn't pay attention to the 404 code to load the right error template.

@samsonasik If you are using the default error templates, they are just placeholders and still need some work.

**Comment by xtreamwayz** [comment]
@samsonasik I have updated the [error templates](https://github.com/xtreamwayz/expressive-composer-installer/tree/master/src/Composer/Resources/templates) of the installer. To get around the problem that the default error page is used when a 404 is triggered: The default error page is checking for a 404 status and if there is one, it displays the output just like the 404 page, Other wise it displays the error object.

**Comment by samsonasik** [comment]
@xtreamwayz I have installed the installer with fresh install from dev-master, and copy my previous middewares. I used "Zend View" when choose templates during install, and still, I need a route match check:
```php
class SugarAction
{
     public function __construct($router) { $this->router = $router; }

     public function __invoke($request, $response, $next) { 
        if (! $this->router->match($request)->isFailure())  {
            $response = $response->withHeader('X-Powered-By', 'JAVA');
        }
        return $next($request, $response);
    }
}
```
I just can't do:
```php
class SugarAction
{
     public function __construct($router) { $this->router = $router; }

     public function __invoke($request, $response, $next) { 
            $response = $response->withHeader('X-Powered-By', 'JAVA');
            return $next($request, $response);
    }
}
```
If i do that, I got 200 OK status even I am on 404 page.

**Comment by xtreamwayz** [comment]
@samsonasik I think I understand now what you mean, but do correct me if I'm wrong. You are trying to do something in the pre/post routing middleware piping and expect a 404 page to be rendered. In this case you are adding a header if there is no valid route match.

That is weird since whatever you add, when the actual middleware is executed and there is no route matched, it should still throw a 404.

Without seeing your code, it looks like you overwrite something somewhere so it is not a 404 error anymore but a normal 200 status.

This is not a real solution, but to force a 404 you can try this. I mean you checked the route and know there isn't one, so you might as well force a 404 and stop the request:
```php
if (! $this->router->match($request)->isFailure())  {
    return $next($request, $response->withStatus(404), 'Not found test');
}
```

**Comment by samsonasik** [comment]
i only have 1 `pre_routing` and i think should not overwrite to 200:
```php
    public function __invoke($request, $response, $next = null)
    {
        $currentPath = $request->getUri()->getPath();

        if (! $this->container->offsetExists('storage') && $currentPath === '/admin') {
            $response = $response->withStatus(403);
            $response->write('Forbidden');

            return $response;
        }

        return $next($request, $response);
    }
```
I think what you meant is `! isSuccess()` instead of `! isFailure()`. I am wondering if we don't need to do that.

**Comment by weierophinney** [comment]
The problem is setting the header. When you do that, you're returning a new
response instance. The final handler compares that to the original, sees a
new instance, and will then return that be instance, not a 404.

So, to get a 404, you have two options:

- Compose the final handler in the above middleware, and inject the
shredded response into it before calling $next().
- Add a post-pipeline middleware to run after any routed middleware (or
pipeline middleware with paths) that converts the response to a 404 and
calls $next() with it. The final handler will treat this correctly.

**Comment by samsonasik** [comment]
@weierophinney yeah, so, I assume what you meant is this ?:
```php
    public function __construct($finalHandler)
    {
        $this->finalHandler = $finalHandler;
    }

    public function __invoke($request, $response, $next = null)
    {
        $response = $response->withHeader('X-Powered-By', 'JAVA');
        $this->finalHandler->setOriginalResponse($response);
       
         return $next($request, $response);
     }
```

**Comment by samsonasik** [comment]
@weierophinney  when I inject the middleware with `Zend\Expressive\FinalHandler` service and call `setOriginalResponse()` with response modified, I now got 404 page. closing, Thanks ;)

**Comment by samsonasik** [comment]
@weierophinney re-open, if i do that, I got 404 status in every page. I still need:
```php
        if (! $this->router->match($request)->isFailure()) {
           $this->finalHandler->setOriginalResponse($response);
           $response = $response->withHeader('X-Powered-By', 'JAVA');
        }
```

**Comment by weierophinney** [comment]
@samsonasik Check your order of operations! You need to set the response in the final handler *after* you change the header, as that operation returns the new response you want the final handler to compare against!

Use this:

```php
if (! $this->router->match($request)->isFailure()) {
   $response = $response->withHeader('X-Powered-By', 'JAVA');
   $this->finalHandler->setOriginalResponse($response);
}
```

**Comment by samsonasik** [comment]
@weierophinney I still get 404 status in every page by doing that. The page is opened, but with status code 404

**Comment by jkhaled** [comment]
Hi there 

i have this config  global.php

```php
 'middleware_pipeline' => [
        'pre_routing' => [
            'middleware'=>'Application\MiddlewareAction',
        ],
        'post_routing' => [
            // See specification below
        ],
    ],
```
but the Middleware's __invoke method never called

```php
 public function __invoke(ServerRequestInterface $request,
                             ResponseInterface $response,
                             $next =null
    ){        
        return $response->getBody()->write("verified");
    }

```
I used  breakpoint (debugger) inside the __invoke($rq, $rs, $nxt)  but , it seems that this method never executed even it exist inside container (sm) 'sconfig

![middleware](https://cloud.githubusercontent.com/assets/2865108/10635315/b3095324-77ef-11e5-891f-9f9fc308c31d.png)

**Comment by weierophinney** [comment]
Please don't hijack existing issues; open a separate issue, please.

(Your issue is invalid config; each item in pre_routing and post_routing
needs to be an array:

```php
'pre_routing' => [
    [ 'middleware' => 'Application\MiddlewareAction' ],
]
```

will solve your issue)

**Comment by jkhaled** [comment]
@weierophinney  yes ! it solved ,
 thank you :),

**Comment by samsonasik** [comment]
@weierophinney why close this?  @jkhaled statement is not related with this issue

**Comment by weierophinney** [comment]
@samsonasik — because I answered the question previously, and cannot reproduce the situation with the details you've provided.
