### ISSUE TITLE
Renaming "Template" to "TemplateRenderer" or "TemplateEngine"?

### ISSUE THREAD

**Issue by danizord** [zendframework/zend-expressive#136]
Maybe it's just me, but I think the current naming sounds a bit confusing.

The `TemplateInterface` currently exposes the public method `render($name, $params = [])`, but a template does not render stuff, it actually gets rendered by a renderer or template engine.

Should we rename `TemplateInterface` to `TemplateEngineInterface` or `TemplateRendererInterface`?

**Comment by bakura10** [comment]
+1. I was a bit surprised too by the naming (same as it was with "Route" defining actually a "Router"). I like TemplateEngineInterface.

**Comment by weierophinney** [comment]
Funny you both noticed that; I've been kicking myself for the naming recently myself. :)

I think `TemplateRendererInterface` makes most sense at this point, as it doesn't model an engine, but a renderer.

@danizord — care to create a pull request?

**Comment by ojhaujjwal** [comment]
I was also a bit surprised by the fact that it is called Template and not TemplateRenderer

**Comment by weierophinney** [comment]
Closed with #139.
