### ISSUE TITLE
AuraRouter, setConfig() on NOTES.md

### ISSUE THREAD

**Issue by adelarcubs** [zendframework/zend-expressive#138]
Hi

I can't find a method named setConfig on Class AuraRouter, on NOTES.md at the part "Hello world, container version, all services defined". I can't find how to fix this :(

Regards

**Comment by samsonasik** [comment]
As @weierophinney said in https://github.com/zendframework/zend-expressive/pull/17#issuecomment-128076087 : 
```
Those notes are, as noted at the top outdated, and really only exist as 
an historical record of decisions made. I fully intend to remove them before we go stable.
```
I think you can read the aura route docs in https://github.com/zendframework/zend-expressive/blob/master/doc/book/router/aura.md for latest configuration for aura router usage.
