### ISSUE TITLE
Adding parameters to templates before render-time

### ISSUE THREAD

**Issue by kynx** [zendframework/zend-expressive#142]
Right now we've only got one chance to add parameters to templates, via `render($name, $params)`.

However it'd be really useful to add data in stages. So a piped middleware could be responsible for populating standard stuff like the current user's name, then the routed middleware adds the stuff it's responsible for.

Plates offers [addData()](http://platesphp.com/templates/data/) that does just this. From what I can tell it's possible in Zend View as well. Twig doesn't, but it could be faked easily enough by storing the data in the Twig bridge until render time.

Anyone else think this is good idea?

**Comment by akrabat** [comment]
Twig has an `addGlobal()` method for this.

**Comment by weierophinney** [comment]
@akrabat - I missed that when we were updating the twig implementation.
Could you maybe do a PR or open an issue against
zend-expressive-twigrenderer to use that instead of the current approach?

**Comment by akrabat** [comment]
Looking at how zend-expressive-zendview is implemented, I'd say that the way the Twig one is done is correct as this way we have per-template default parameters which isn't supported by Twig's `addGlobal`.

However, I don't see a way to add a parameter to every template as per the example in this issue?

**Comment by akrabat** [comment]
Ah -  there's a weird template name called "TEMPLATE_ALL"… I would *never* have guessed that!

**Comment by weierophinney** [comment]
Evidently I need to make that more prominent in the docs... Any suggestions?

We could still have that proxy to twig's global, while providing the
abstraction for per-template. Thoughts?

**Comment by weierophinney** [comment]
Closed with #143
