### ISSUE TITLE
Config autoload fails when splitting routes in different files

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zend-expressive#150]
This issue is either for zend-expressive or zend-expressive-skeleton, depending on the solution. However issues are not yet activated for the skeleton project.

The problem arises when you split routes into different files. E.g. you have a routes.admin.global.php with this:

```php
    'routes' => [
        [
            'name' => 'admin.dashboard',
            'path' => '/admin/dashboard',
            'middleware' => App\Admin\Dashboard\Index::class,
            'allowed_methods' => ['GET'],
        ],
    ],
```

and a routes.api.global.php with this:

```php
    'routes' => [
        [
            'name' => 'api',
            'path' => '/api/{resource:[a-z]+}[/{resourceId:\d+}[/{relation:[a-z]+}[/{relationId:\d+}]]]',
            'middleware' => App\Api\ApiMiddleware::class,
            'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        ],
    ],
```

When merging the two files they overwrite each other because they have the same key. There are two possible solutions.

1. Use the name as a key:

    ```php
    'routes' => [
        'api' => [
            'path' => '/api/{resource:[a-z]+}[/{resourceId:\d+}[/{relation:[a-z]+}[/{relationId:\d+}]]]',
            'middleware' => App\Api\ApiMiddleware::class,
            'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        ],
    ],
    ```

2. Use zend-stdlib in ``config/config.php`` in the skeleton. The config.php file looks then like this:

    ```php
    use Zend\Stdlib\ArrayUtils;
    use Zend\Stdlib\Glob;
    
    $cachedConfigFile = 'data/cache/app_config.php';
    
    $config = [];
    if (is_file($cachedConfigFile)) {
        // Try to load the cached config
        $config = json_decode(file_get_contents($cachedConfigFile), true);
    } else {
        foreach (Glob::glob('config/autoload/{{,*.}global,{,*.}local}.php', Glob::GLOB_BRACE) as $file) {
            $config = ArrayUtils::merge($config, include $file);
        }
    
        // Cache config if enabled
        if (isset($config['config_cache_enabled']) && $config['config_cache_enabled'] === true) {
            file_put_contents($cachedConfigFile, json_encode($config));
        }
    }
    
    // Return an ArrayObject so we can inject the config as a service in Aura.Di
    // and still use array checks like ``is_array``.
    return new \ArrayObject($config, \ArrayObject::ARRAY_AS_PROPS);
    ```

Personally I use option 2 anyway, but this adds an extra dependency on zend-stdlib.

**Comment by weierophinney** [comment]
@xtreamwayz One thing to try is zend-stdlib `ArrayUtils::merge()`, which is what zend-config uses internally. It has a number of features to intelligently merge indexed arrays so that they do not overwrite; I tend to use that anywhere I might normally use `array_merge` or `array_merge_recursive` if the values are non-scalar. In this particular case, I think the extra dependency is very much worth it.

**Comment by jkhaled** [comment]
Hi, 
@weierophinney  In zend-expressive-skeleton , all the config (dependencies) files must be in config/autoload folder, so when we use many modules we got large number of config files,  in my opinion i think the separation of configs that is used in zf2 is more arranged.

**Comment by weierophinney** [comment]
@jkhaled We're suggesting the same solution here. :wink:

**Comment by xtreamwayz** [comment]
This is fixed now with zendframework/zend-expressive-skeleton#7.
