### ISSUE TITLE
Adding a new type of route

### ISSUE THREAD

**Issue by Stanimirdim92** [zendframework/zend-expressive#157]
Is it possible to include another type of route? I'm talking about this one. https://github.com/gatakka/PGF-Router The [performance](https://github.com/gatakka/PGF-Router#performance) is quite good and it doesn't uses regular expressions.

**Comment by weierophinney** [comment]
I suggest writing a `RouterInterface` adapter and, potentially, a service container factory for the implementation, and publishing a repository with those. We can then link to it in our documentation as an alternative, and, if enough people are using it, add it to the skeleton installer.

For examples of packages publishing routers, please see:

- https://github.com/zendframework/zend-expressive-aurarouter
- https://github.com/zendframework/zend-expressive-fastroute
- https://github.com/zendframework/zend-expressive-zendrouter
