### ISSUE TITLE
Dispatcher middleware?

### ISSUE THREAD

**Issue by mtymek** [zendframework/zend-expressive#16]
I would like to propose adding additional layer to execution stack - dispatcher. 

Currently routing process passes execution directly to matched middleware (which acts as "controller" in MVC app). In my proposal, router injects routing result into an attribute of request object, which is later used by dispatcher to locate and execute the controller. 
With this setup you gain a lot of flexibility - for example you could build a dispatcher that accepts returning `ViewModel` from controller, emulating ZF2's MVC.

See following code:

```php
// router
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next) 
{
    $request = $request->withAttribute('route_match', $this->router->match($request));
    return $next($request, $response);
}

// dispatcher
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next) 
{
    if ($match = $request->getAttribute('route_match')) {
	$controller = $this->container->get($match->getControllerName());

	$result = $controller($request, $response);

        // got response - return it
	if ($result instanceof ResponseInterface) {
	    return $result;
	}
 
        // got array - convert it to ViewModel and proceed
	if (is_array($result)) {
	    $result = new ViewModel($result);
	}

         // got view model - render it and inject output into response
	if ($result instanceof ViewModel) {
	    return $this->renderViewModelIntoResponse($response, $result);
	}
    }

    return $next($request, $response);
}
```

Does it fit into scope of `zend-expressive`?

**Comment by weierophinney** [comment]
> Does it fit into scope of zend-expressive?

We've been debating it, and I have a few pros and cons to the approach and similar ones we've discussed.

However, the deciding factor is this:

> returning anything other than a response breaks the contract of middleware and removes its re-usability/composability in other middleware stacks, as it's now dependent on the environment in which it is invoked.

As such, a dispatcher is not in the scope of zend-expressive, or Stratigility.

---

Regarding your specific use case, **templating**, however, we do have two ideas:

- First is to define a `TemplatingInterface`, and provide some implementations around common/popular templating solutions (we're targeting Twig, Plates, `Zend\View`, and potentially mustache to start). Middleware would accept the `TemplatingInterface` as a dependency, and then call on it when creating the response:

  ```php
  return new HtmlResponse($this->template->render($name, $vars));
  ```

  Along with this, we're considering having either an `AbstractFactory` for middleware that only needs a `TemplatingInterface`, and/or a combination of an Aware interface + DelegatorFactory to obviate the need to define a factory for middleware that uses templating. I prefer injecting all dependencies via constructors, but usability and simplicity of service registration is a goal of this project.

- Second is to utilize custom `Zend\Diactoros\Response\EmitterInterface` implementations. My patch in #7 provides an `EmitterStack`; the goal of this was to allow registering emitters that introspect the response to determine how to best render it. One potential use case would be for templated responses. My concern with this approach, however, is similar to my concern about using dispatchers: while we'd be returning a response still, we now depend on the runtime environment being capable of doing something with that response. Such an approach would negatively impact reusability of middleware that depends on the emitter capabilities.

As such, we'll likely only implement the first point.

---

One last point: in your example, you have the following:

```php
$request = $request->withAttribute('route_match', $this->router->match($request));
```

The current implementation injects all parameters matched by the router as separate attributes already. :)

**Comment by mtymek** [comment]
Thanks for your explanation - it makes perfect sense :)

There's one more issue that's bothering: if you add matched params to separate attributes, there is a chance that they will conflict with another attributes, that are set by different middleware (for instance: https://github.com/oscarotero/psr7-middlewares). Setting all of them in single attribute (`route_match`) reduces this risk. What's your opinion here?
