### ISSUE TITLE
Avoid composed words in repo packages

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-expressive#165]
Instead `zend-expressive-aurarouter` I would prefer `zend-expressive-aura` or `zend-expressive-router-aura`

**Comment by moderndeveloperllc** [comment]
If you were to split this out, it should be consistent, and across the renderers too:
`zend-expressive-router-zend`
`zend-expressive-router-aura`
`zend-expressive-router-fastroute`
`zend-expressive-renderer-zendview`
`zend-expressive-renderer-plates`
`zend-expressive-renderer-twig`
