### ISSUE TITLE
zend-servicemanager 3 before v1 of Zend-Expressive

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#171]
That's all.

**Comment by danizord** [comment]
:+1:

**Comment by weierophinney** [comment]
Already working on integration with the installer, but have a few issues to
iron out. It'll happen. :-)

**Comment by xtreamwayz** [comment]
@weierophinney What issue you have with the installer? I've got it working here. It should be something like this:

Edit this ``src/Composer/Resources/config/container-zend-servicemanager.php``
```php
<?php

use Zend\ServiceManager\ServiceManager;

// Load configuration
$config = require 'config.php';
$dependencies = $config['dependencies'];

// Inject config as a service
$dependencies['services']['config'] = $config;

// Build container
$container = new ServiceManager($dependencies);

return $container;
```

Change in ``src/Composer/config.php``
```
'zendframework/zend-servicemanager'              => 'dev-master',
```

**Comment by xtreamwayz** [comment]
@weierophinney oh never mind... You have issues, but probably not with the installer. I read that wrong.

**Comment by weierophinney** [comment]
@xtreamwayz correct; issues are getting dependencies working together. :)

**Comment by weierophinney** [comment]
This isn't going to happen, and, with the changes I've proposed in zendframework/zend-servicemanager#59 and zendframework/zend-servicemanager#60, no changes will be necessary to jump to v3 anyways. :smile:
