### ISSUE TITLE
Expressive modules

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-expressive#174]
I like the idea of zf2 modules. It would be useful to have this functionality in expressive application by default. Ideally before v. 1.0 release comes.

**Comment by snapshotpl** [comment]
You can check this one https://github.com/mtymek/modular-expressive

**Comment by vaclavvanik** [comment]
Yeah I saw that repo. I think modules functioanality is high-useful and therefore should be supported by default.

**Comment by snapshotpl** [comment]
https://github.com/mtymek/modular-expressive#limitations

If you want to use fullstack framework use ZF2 or wait for ZF3 ;)

**Comment by RalfEggert** [comment]
There is a cookbook recipe for modular applications now. It is quite easy to setup.

http://zend-expressive.readthedocs.org/en/latest/cookbook/modular-layout/

@weierophinney 
Maybe the issue could be closed? I guess it will not be supported by default, will it?

**Comment by weierophinney** [comment]
@RalfEggert we may add the mtymek/expressive-config-manager to the skeleton (and/or organization!) in the future, but, as you note, it's usable today already, and documented. Closing!
