### ISSUE TITLE
Middleware not getting called

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-expressive#179]
Hi, 

I am working on expressive with Aura.Di . Added a middleware basically as simple as 

```php
<?php
namespace App\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class IsAuthenticated
{	
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {		
        var_dump("Hello World");
        exit;
    }
}
```

and this middleware is added in the `config/autoload`

```php
// in middleware-pipeline.global
return [    
    'middleware_pipeline' => [        
        'pre_routing' => [
            [             
                'middleware' => 'App\Middleware\IsAuthenticated',             
                'error' => true,
            ],            
        ],
        'post_routing' => [           
        ],
    ],
];
```

The service is also defined in the container.  For some reason the class is never called.

I tried a few other variations like 

```php
$app->pipe('App\Middleware\IsAuthenticated');
$app->run()
```

```php
$app->pipe($di->get('App\Middleware\IsAuthenticated'));
$app->run()
```

```php
$app->pipe('/', $di->get('App\Middleware\IsAuthenticated'));
$app->run()
```

But didn't get the expected result `Hello World` dumped.

**Comment by moderndeveloperllc** [comment]
I think it's not getting called because you set `error => true` for that middleware. Per the [docs](https://github.com/zendframework/zend-expressive/blob/master/doc/book/usage-examples.md):

> `error` indicates whether or not the middleware represents error middleware; this is done to ensure that lazy-loading of error middleware works as expected.

**Comment by xtreamwayz** [comment]
If you mark middleware as error middleware, it loads only when an error is triggered. Besides that, the invoke function should be written differently:

```php
public function __invoke($err, $req, $res, $next)
```

**Comment by harikt** [comment]
cool. Thank you.

Looking at `middleware-pipeline.global.php` I thought error was to display the error if anything happened :) .

Thanks guys! . This works as expected.
