### ISSUE TITLE
Using $this in route clousure?

### ISSUE THREAD

**Issue by lauthiamkok** [zendframework/zend-expressive#184]
I notice that we cannot $this like in Slim 3 in the current version of Expressive

```
$app->route('/hello/{name}', function ($request, $response, $next) {
    $container = $this->getContainer();
    $name = $request->getAttribute('name');
    $response->getBody()->write('Hello, ' . $name);
    return $response;
});
```

I will get an an error for that above. I have to pass in $app via use which is not as neat as Slim:

```
$app->route('/hello/{name}', function ($request, $response, $next)  use ($app) {
    $container = $app->getContainer();
    $name = $request->getAttribute('name');
    $response->getBody()->write('Hello, ' . $name);
    return $response;
});
```

Would you make that possible in the future versions?

**Comment by Maks3w** [comment]
What error did you receive? Are you using PHP 5.5+?

**Comment by lauthiamkok** [comment]
I get this error:

`Fatal error: Using $this when not in object context in C:...\public\index.php on line..`

And I am on PHP5.6

**Comment by xtreamwayz** [comment]
It looks like Slim binds the closure to the [$app instance](https://github.com/slimphp/Slim/blob/3.x/Slim/Route.php#L101) and this is not happening in Expressive at the moment.

**Comment by lauthiamkok** [comment]
I would do that `$callable = $callable->bindTo($this->container);` if I were ...

**Comment by Maks3w** [comment]
Thx @xtreamwayz 

TBH I don't like the Slim way. It's too magic for me guess what `$this` means. Also remember me all the nightmares `this` has on JavaScript.

**Comment by lauthiamkok** [comment]
Well, this is PHP. 

`It's too magic for me guess what `$this` means`

 Only Python does it right! ;)

**Comment by xtreamwayz** [comment]
Same here. When you add ``use (app)`` you know exactly where it comes from. Besides that, for Slim it's more useful than for Expressive since Slim has a lot of proxy methods in it $app class for the router and container.

**Comment by weierophinney** [comment]
This is not a feature I want to enable.

One goal for Expressive is to also encourage best practices. This means using dependency injection, not pulling dependencies from the container within your middleware. If you will be using closures, then you should be passing the app, container, or the actual dependency explicitly; this makes understanding where the instances came from traceable.

As @xtreamwayz notes, the `Application` class in Expressive has very little utility beyond registering middleware or retrieving the container; it makes more sense to pass the container explicitly to a closure.
