### ISSUE TITLE
PHPTAL as another template engine

### ISSUE THREAD

**Issue by wwwgo-pl** [zendframework/zend-expressive#201]
http://phptal.org/
Has anyone considered adding this template engine to Zend-Expressive?
Pros:
- Automatic XSS protection
- Easily change between html / xml output
- Input has to be valid html / xml

Recently I have added this template engine to Slim 3 (https://github.com/wwwgo-pl/Slim3-Phptal) but I don't have enough knowlege of ZE.

**Comment by harikt** [comment]
Hi,

The one thing you need to implement is https://github.com/zendframework/zend-expressive/blob/master/src/Template/TemplateRendererInterface.php .

You can see examples like https://github.com/zendframework/zend-expressive-zendviewrenderer , https://github.com/zendframework/zend-expressive-twigrenderer etc.

**Comment by Bittarman** [comment]
I'm closing this as it doesn't appear to actually be an issue, more of a support request.
