### ISSUE TITLE
ObserverManager container entry

### ISSUE THREAD

**Issue by renanbr** [zendframework/zend-expressive#215]
Regarding to the nice :sparkles: route observer feature

To access `Zend\Expressive\Application` through the application is a good practice? I don't think so, and if you agree...
I think we should move `(attach|detach|notify)RouteResultObserver()` and related methods to another container entry (e.g. `Zend\Expressive\Router\ObserverManager::class`). Then users middlewares may register route observers following the best practices, through the container entries.

As consequence we inject a dependency to the application class.

**Comment by weierophinney** [comment]
What benefit does this give? How would pushing this into another class benefit users?

Triggering the route result observers is an *application-level* concern, to ensure consistency. (We did not push it into the routers, as that could lead to inconsistencies in implementations.) How would we enforce that the same manager instance is used in standalone usage of Expressive?

Also, I don't understand this statement:

> To access Zend\Expressive\Application through the application is a good practice?

What exactly do you mean?

**Comment by renanbr** [comment]
I thought the benefit would be having a specific class for a specify job (see my notes at the end).

About good practices, in my personal tries with Expressive, I avoided to build middlewares that depend to `Application` or `Container` instances.
The current documentation ([configuring route result observer via the observer factory](https://github.com/zendframework/zend-expressive/blob/master/doc/book/router/result-observers.md#via-the-observer-factory)) may encourage people to use `Application` as a dependency. So I thought this feature could may be moved, just to minimize this user (my) behavior.

But after this fantastic explanation at https://github.com/zendframework/zend-expressive/issues/216#issuecomment-162923176 I’m not sure if decoupling this feature from Application class is the best solution, once all route features are embedded over there. Now it makes sense for me why middlewares may depends to `Application` class. Thanks again.

**Comment by weierophinney** [comment]
> Now it makes sense for me why middlewares may depends to Application class

I'm still not sure I understand this statement, to be honest! Middleware should *not* depend on the `Application` class; they're simply registered with it; the application *pulls* middleware from the container. As such, they should be independent and re-usable in any PSR-7 middleware stack. Can you perhaps elaborate on what you mean with the above statement? (just to satisfy my curiosity!)

**Comment by renanbr** [comment]
I will try with an example, just for explanation... we would want to register the route name when user send a query parameter `log=on`

```php
// registered as RouteLoggerMiddleware::class in config with its respective factory
// referenced into 'middleware_pipeline' > 'pre_routing'
class RouteLoggerMiddleware implements RouteResultObserverInterface
{
    public function __construct(Application $app, LoggerInterface $logger) { /* ... */ }

    public function __invoke($req, $res)
    {
        if ($req->getAttribute('log') == 'on') {
            // here is the key, add in runtime route result observers
            $this->app->attachRouteResultObserver($this);
        }
        // ...
    }

    public function update(RouteResult $result)
    {
        $this->logger->info('route: ' . $result->getMatchedRouteName());
    }
}

class RouteLoggerMiddlewareFactory
{
    public function __construct(Container $container)
    {
        return new RouteLoggerMiddleware(
            $container->get(Application::class),
            $container->get(LoggerInterface::class)
        );
    }
}
```

**Comment by weierophinney** [comment]
Swap the `Application` typehint for `RouteResultSubjectInterface`; then alias the `Application` service to that interface in your DI container, and you've successfully de-coupled from the zend-expressive package:

```php
class RouteLoggerMiddleware implements RouteResultObserverInterface
{
    public function __construct(RouteResultSubjectInterface $subject, LoggerInterface $logger)
    {
        /* ... */
    }

    public function __invoke($req, $res)
    {
        if ($req->getAttribute('log') == 'on') {
            // here is the key, add in runtime route result observers
            $this->subject->attachRouteResultObserver($this);
        }
        // ...
    }

    public function update(RouteResult $result)
    {
        $this->logger->info('route: ' . $result->getMatchedRouteName());
    }
}

class RouteLoggerMiddlewareFactory
{
    public function __construct(Container $container)
    {
        return new RouteLoggerMiddleware(
            $container->get(RouteResultSubjectInterface::class),
            $container->get(LoggerInterface::class)
        );
    }
}
```

If you're using zend-servicemanager:

```php
return [
    'dependencies' => [
        'aliases' => [
            RouteResultSubjectInterface::class => Application::class,
        ],
    ],
];
```

In pimple:

```php
$container[RouteResultSubjectInterface::class] = function ($container) {
    return $container->get(Application::class);
};
```

In Aura.dDi:

```php
$container->set(
    RouteResultSubjectInterface::class,
    $container->lazyGet(Application::class)
);
```

In other words, the coupling can occur *in your application*, vs in your middleware and/or middleware-specific factories. We leverage that even in our own packages, to help reduce dependencies and coupling (see the zend-expressive-helpers tests!).

**Comment by renanbr** [comment]
what an elegance :wink: thanks again!
