### ISSUE TITLE
[Cookbook] How to setup localization

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive#226]
A suggestion for the cookbook: How to setup the localization?

Let's say in the routing is a `lang` parameter which defines the current language. This should be used to set the locale for the application. How can this be archieved? Are their multiple ways to handle this? Which way is the most recommended way?

**Comment by weierophinney** [comment]
I presented a potential solution in #199

**Comment by RalfEggert** [comment]
Ok, thanks for the link. I must have missed it. How could that solution be combined with the routing? Should it be placed in the `post_routing` pipeline? 

When I played around with a Middleware it only worked for `pre_routing` but wasn't called for `post_routing`. Here is my test middleware which is just setting the locale without an access to the routing for testing:

```
namespace Application\I18n;

use Locale;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class LocalizationMiddleware
{
    public function __invoke(
        ServerRequestInterface $request,
        ResponseInterface $response,
        callable $next
    ) {
        Locale::setDefault('de_DE');

        return $next($request, $response);
    }
}
```

When I add it here, it works:

```
return [
    'dependencies' => [
        'invokables' => [
            Application\I18n\LocalizationMiddleware::class =>
                Application\I18n\LocalizationMiddleware::class,
        ],
    ],

    'middleware_pipeline' => [
        'pre_routing' => [
            [
                'middleware' => [
                    Application\I18n\LocalizationMiddleware::class,
                ],
            ],
        ],

        'post_routing' => [
        ],
    ],
];
```

When I add it here, it doesn't:

```
return [
    'dependencies' => [
        'invokables' => [
            Application\I18n\LocalizationMiddleware::class =>
                Application\I18n\LocalizationMiddleware::class,
        ],
    ],

    'middleware_pipeline' => [
        'pre_routing' => [
        ],

        'post_routing' => [
            [
                'middleware' => [
                    Application\I18n\LocalizationMiddleware::class,
                ],
            ],
        ],
    ],
];
```

Is the configuration for a `post_routing` middleware different than for a `pre_routing` middleware?

**Comment by harikt** [comment]
@RalfEggert are you calling the `$next()` from inside the action ? If not the `post_routing` will not work. Related https://github.com/zendframework/zend-expressive/issues/198

**Comment by weierophinney** [comment]
post_routing middleware is piped to the application *after* the routing
middleware. This means it will only execute:

- if routing fails, or
- an error occurs (only error middleware gets executed in this case,
however), or
- routed middleware calls $next

Based on the middleware you've listed as an example, where you're setting
the locale, you likely want pre_routing anyways, as you're setting the
locale to use on this request.

**Comment by weierophinney** [comment]
If you want it combined with routing - i.e., only specific does need locale
awareness - use arrays of middleware for the matched middleware when
creating a route:

```php
[
    'route' => '/foo/bar'
    'middleware' => [
        /* multiple middleware entries here */
]
```

This feature was added in RC3.

**Comment by RalfEggert** [comment]
@weierophinney 

Thanks for explanation. I thought that `post_routing` middleware is called after the routing process and before the action dispatching. If it would have been called `post_dispatching` it would have be much clearer to me from beginning.

You combination with routing would probably work but be to much effort if I need to add it to each route. I was thinking that all my routes have a `/:lang` route parameter and I would like to set the locale depending on this with my Middleware. But if the `pre_routing` middleware is actually called before the routing than this parameter would not have been determined yet.

**Comment by RalfEggert** [comment]
I will play around with this during the day. Maybe that is a better solution for my problem.

http://zend-expressive.readthedocs.org/en/latest/router/result-observers/

**Comment by RalfEggert** [comment]
Well, I came up now with this class:

```
namespace Application\I18n;

use Locale;
use Zend\Expressive\Router\RouteResult;
use Zend\Expressive\Router\RouteResultObserverInterface;

class LocalizationObserver implements RouteResultObserverInterface
{
    public function update(RouteResult $result)
    {
        if ($result->isFailure()) {
            return;
        }

        $matchedParams = $result->getMatchedParams();

        if (isset($matchedParams['lang'])) {
            Locale::setDefault($matchedParams['lang']);
        } else {
            Locale::setDefault('de_DE');
        }
    }
}
```

I configured it in the `dependencies.global.php` and attached it to my app in the `index.php`.

```
use Application\I18n\LocalizationObserver;

[...]

$app = $container->get('Zend\Expressive\Application');
$app->attachRouteResultObserver(
    $container->get(LocalizationObserver::class)
);
$app->run();
```

I don't know if this is a good practice or rather a bad one? 

Anyway would be nice If I don't need to amend the `index.php`. But is writing my own factory for key `Zend\Expressive\Application` the best way to do it? Or would a config param make sense?

**Comment by weierophinney** [comment]
First off, this is a great use for the route result observers!

There are five approaches you can take, each with pros and cons:

- Registration via the bootstrap script
- Registration in the observer's factory
- Registration via a delegator factory
- Registration via an extension of the Application factory
- Registration via pre_routing middleware

## Bootstrap script

You can do just as you've done in your above example, and modify your bootstrap script. This is likely the simplest way, but means that there may be a growing amount of code in that file.

## Observer factory

Alternately, in the factory for your observer, have it self-attach to the application instance:

```php
// get instance of observer...

// and now check for the Application:
if ($container->has(Application::class)) {
    $container->get(Application::class)->attachRouteResultObserver($observer);
}

return $observer;
```

There are two things to be careful of with this approach:

- Circular dependencies. If a a dependency of the Application is dependent on your observer, you'll run into this.
- Late registration. If this is injected as a dependency for another class after routing has happened, then your observer will never be triggered.

If you can prevent circular dependencies, and ensure that the factory is invoked early enough, then this is a great, portable way to accomplish it.

## Delegator factory

If you're using zend-servicemanager, you can use a delegator factory on the Application service to pull and register the observer:

```php
use Zend\Expressive\Application;
use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class ApplicationObserverDelegatorFactory implements DelegatorFactoryInterface
{
    public function createDelegatorForName(
        ServiceLocatorInterface $container,
        $name,
        $requestedName,
        $callback
    ) {
        $application = $callback();

        if (! $container->has(LocalizationObserver::class)) {
            return $application;
        }

        $application->attachRouteResultObserver(
            $container->get(LocalizationObserver::class)
        );
        return $application;
    }
}
```

Then register it as a delegator factory in `config/autoload/dependencies.global.php`:

```php
return [
    'dependencies' => [
        'delegator_factories' => [
            Zend\Expressive\Application::class => [
                ApplicationObserverDelegatorFactory::class,
            ],
        ],
        /* ... */
    ],
];
```

This approach removes the probability of a circular dependency, and ensures that the observer is attached as early as possible.

The problem with this approach, though, is portability. You can do something similar to this with Pimple:

```php
$pimple->extend(Application::class, function ($app, $container) {
    $app->attachRouteResultObserver($container->get(LocalizationObserver::class));
    return $app;
});
```

and there are ways to accomplish it in Aura.Di as well — but they're all different, making the approach non-portable.

## Extend the Application factory

Alternately, extend the Application factory:

```php
class MyApplicationFactory extends ApplicationFactory
{
    public function __invoke($container)
    {
        $app = parent::__invoke($container);
        $app->attachRouteResultObserver($container->get(LocalizationObserver::class));
        return $app;
    }
}
```

Then alter the line in `config/autoload/dependencies.global.php` that registers the `Application` factory to point at your own factory.

This approach will work across all container types, and is essentially a portable way of doing delegator factories.

## Use middleware

Alternately, use `pre_routing` middleware to accomplish the task; the middleware will get both the observer and application as dependencies, and simply register the observer with the application:

```php
use Zend\Expressive\Router\RouteResultSubjectInterface;

class LocalizationObserverMiddleware
{
    private $application;
    private $observer;

    public function __construct(LocalizationObserver $observer, RouteResultSubjectInterface $application)
    {
        $this->observer = $observer;
        $this->application = $application;
    }

    public function __invoke($request, $response, callable $next)
    {
        $this->application->attachRouteResultObserver($this->observer);
        return $next($request, $response);
    }
}
```

The factory would inject the observer and application instances; I'm sure you can figure that part out on your own.

In your `config/autoload/middleware-pipeline.global.php`, you'd do the following:

```php
return [
    'dependencies' => [
        'factories' => [
            LocalizationObserverMiddleware::class => LocalizationObserverMiddlewareFactory::class,
            /* ... */
        ],
        /* ... */
    ],
    'middleware_pipeline' => [
        'pre_routing' => [
            [ 'middleware' => LocalizationObserverMiddleware::class ],
            /* ... */
        ],
        'post_routing' => [
            /* ... */
        ],
    ],
];
```

This approach is also portable, but, as you can see, requires more setup (a middleware class + factory + factory registration + middleware registration). On the flip side, it's portable *between applications*, which could be something to consider if you were to make the functionality into a discrete package.

(This is the approach we took for the ServerUrl and Url helpers.)

**Comment by RalfEggert** [comment]
Thanks for the detailed reply.

The problem I have with the Observer factory for my observer is that this factory needs to be called somewhere. Otherwise it won't be executed. So I need to add a `$container->get(LocalizationMiddleware::class)` somewhere. If I understand it correctly this woul need some extra coding. 

So I would prefer one of the last three solutions.

**Comment by RalfEggert** [comment]
@weierophinney 

I created a PR with a new recipe for this problem. Most text is from your detailed answer and I added some other parts. Might need to be corrected by a native speaker.

**Comment by RalfEggert** [comment]
Well, I have another issue with this localization and the `lang` route param. To be precise, there are two issues

### Url view helper ###

When the routes contain a `lang` route param it is not possible to get it merged automatically when using the `url` view helper. I had a closer look at the view helper. When no route is passed to the `__invoke()` method than the matched route params are merge within the `generateUriFromResult` method. When the `result` was set by the observer the matched route params are only merged when the matched route name is the same than the passed route name. 

https://github.com/zendframework/zend-expressive-helpers/blob/master/src/UrlHelper.php#L47

In the "original" url view helper there is an optional flag that can be set to handle such situations when I want to merge matched route params. 

Or is there another way to merge the matched route params for each call of the url view helper?

### Redirecting within an action middleware ###

Normally I do my redirecting like this:

```
return new RedirectResponse(
    $this->router->generateUri('my-route')
);
```

At this point I have no access to the route result. I could implement the `RouteResultObserverInterface` for each middleware but that sound like a bad solution. Since there is no helper like the controller plugins in the classical MVC, how could this be handled?

**Comment by xtreamwayz** [comment]
I wanted to say that Symfony has a special _locale parameter for url's. Maybe we can add something like that as well.

But on a second thought... By the time the application gets into the action middleware, the routeresult is injected inside the request object and inside the container right? At least I think I read something like that. I'm pretty sure I did a request var_dump once inside an action and I saw the routeresult there.

**Comment by RalfEggert** [comment]
@xtreamwayz 

No, the RouteResult is not attached to the Router. I just dumped it myself. But your idea with the request attributes is a good one.

This just leaves the view helper issue. Currently, I am thinking of overwriting the Url view helper to add the language param every time.

**Comment by xtreamwayz** [comment]
> just notices that the RouteResult is accessible by the Request! Nice one!

That's the one I meant. I just didn't remember how to access it.

**Comment by weierophinney** [comment]
If you import the `RouteResult` class, you can make this simpler:

```php
$request->getAttribute('Zend\Expressive\Router\RouteResult')
```

becomes

```php
$request->getAttribute(RouteResult::class)
```

**Comment by RalfEggert** [comment]
Added PR #244 with another recipe for language setting.

**Comment by RalfEggert** [comment]
Since both PR #227 and #244 are closed, can this issue be closed too?

**Comment by weierophinney** [comment]
Completed with #227 and #244.
