### ISSUE TITLE
Async and Parallel configuration or implementation incorporation to ZF3 segments/Mods

### ISSUE THREAD

**Issue by ganeshkbhat** [zendframework/zend-expressive#229]
I am trying async with parallel and seem to be having better implementation. I might be wrong here. But this is something I surely would want Zend to address which seems missing. SM and Events is the place where I would use this. Didnt know exactly were to put this message. But since this is in RC I surely recommend this on your cards for ZF3. Useful for Logging, simultaneous DB+authACLChecks, etc.

https://github.com/reactphp/promise#introduction

**Comment by weierophinney** [comment]
We already have service manager integration (the `Application` instance requires a container implementation, and the installer even prompts you to select one!).

With regards to events, we are purposely omitting them from the runtime. The runtime does exactly two things:

- Provides and executes a middleware pipeline.
- Provides routing middleware.

There's no need for events as we have them in ZF2 in this workflow, as the pipeline essentially serves the same purpose. That said, *there's nothing preventing you from adding events within code that you expose through middleware.* We, in fact, encourage you to use events where you feel they could be useful, and we will likely ship some middleware that will use them (e.g., authentication/authorization middleware, which we will likely model in a similar fashion to what we did in zfcampus/zf-mvc-auth).

What I'm really wondering about is your link to `ReactPHP`. React provides a mechanism for doing asynchronous request processing, which is very different from the zend-eventmanager implementation (which is more along the lines of signal-slot, subject/observer, and the like). If you're interested it In terms of async processing, they're essentially compatible already; we can translate from ReactPHP request/response to PSR-7 and back, and have ReactPHP dispatch an Expressive application already.

**Comment by ganeshkbhat** [comment]
Parallel is sure out of question I believe since it is a external extension and will create complication for expressive. Middleware of NodeJS works fast due to Async nature of it added to the simplicity of design.  Here is why I recommended relook into designs with async or refactoring. As soon as I have defaults in with Zend mods I am used to, say Zend SM and Zend Router (for api and no view/templating deps) the code drags. I am comparing Slim (PSR7), Expressive(PSR7), Lucarest, and Apigility. That is the order of performance.

Clean Route Performance on PHP7 on PHPDev server on Win8: Slim('/' at 15-20ms), Expressive(PSR7 support, '/' at 350-400ms), Lucarest ( '/' at 400-500ms), and Apigility ('/' at 700-800ms). 

Will come back with details if there's something that I can add.

**Comment by weierophinney** [comment]
I've benchmarked, and zend-view + the zend-mvc router are the slowest
combination — which is why the default options are FastRoute + Plates. Try
those, and I suspect you'll see quite different performance profiles.

(The zend components will get a large boost once we've released the v3
versions, as the service manager and event manager, which each consum, are
far faster on those.)

**Comment by ganeshkbhat** [comment]
Let me try Fastroute. I am not using view since I am trying to work my way out for Rest API. I have independent clients. Let me come back on if Fastroute gives better performance. It should like you said. But with service manager and like for logging, its on blocking mode; as vanilla php is supposed to be. +few more ms or secs. I am actually waiting for ZF3.

**Comment by weierophinney** [comment]
@ganeshkbhat I don't think you know what you mean when you say you're "waiting for ZF3." :smile: 

Please read the following posts:

- http://framework.zend.com/blog/announcing-the-zend-framework-3-roadmap.html
- http://framework.zend.com/blog/announcing-expressive.html
- http://framework.zend.com/blog/zend-framework-3-update-and-roadmap.html
- http://framework.zend.com/blog/2015-12-10-zf3-biweekly-update.html

ZF3 is an *initiative*, and not a discrete release. Expressive is a complementary offering to zend-mvc, not a replacement, and we are adding features to zend-mvc to allow dispatching middleware, as well as planning ways to dispatch ZF1/ZF2 applications as middleware.

One of the points of Expressive is to allow *you* to choose the libraries *you* need, based on the criteria your application presents. You are not forced to use ZF components; choose components from whatever library you want, based on how they fulfill the criteria you present. If the ZF logger is presenting too much overhead, use Monolog or something else.

**Comment by ganeshkbhat** [comment]
Yes, I am sorry. I saw that after a day in a corner, and realized what a duh I was. May be, I was on developer fatigue of a long day. :-) Frankly, Expressive actually has made it easy. The implementation sure is lighter. Just a thought, if you can add the visual structure, flow process, and use cases (do's/dont's) of expressive in a single introduction page to docs it will be an ice-ing on the cake. I see that middleware can completely block functionality of future codes if something is done wrong.

**Comment by weierophinney** [comment]
> I see that middleware can completely block functionality of future codes if something is done wrong.

Well, that's true anywhere. :wink: 

Can you create a separate issue for this, please:

> if you can add the visual structure, flow process, and use cases (do's/dont's) of expressive in a single introduction page to docs it will be an ice-ing on the cake.

That way we can track those items separately. It's likely too late for me to do anything for the stable release, but they're definitely things I want to address in the documentation.

**Comment by ganeshkbhat** [comment]
I surely meant I am getting used to ($req, $res, $next) :-). Sure, Let me raise as a different doc issue request.
