### ISSUE TITLE
Add example github projects to documention

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zend-expressive#231]
Would it be helpful to add a page with expressive based github projects to the documentation?

Examples
- https://github.com/codeliner/php-ddd-cargo-sample
- https://github.com/AndrewCarterUK/AstroSplash

Personal blogs
- https://github.com/weierophinney/mwop.net
- https://github.com/xtreamwayz/xtreamwayz.com
- https://github.com/acelaya/website-expressive

**Comment by codeliner** [comment]
of course +1 from my side ;)

**Comment by RalfEggert** [comment]
Don't forget https://github.com/RalfEggert/zend-expressive-tutorial when its ready... ;-)

**Comment by xtreamwayz** [comment]
See pull request #233
