### ISSUE TITLE
Allow to segregate middleware on host

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#235]
Hi,

Similar to how we can segregate by path:

``` php
[
                'path'       => '/api',
                'middleware' => [
                    ApiAuthenticationMiddleware::class,
                    AuthorizationMiddleware::class
                ]
            ]
```

Would it be possible to also segregate by host?

``` php
[
                'host'       => 'api',
                'middleware' => [
                    ApiAuthenticationMiddleware::class,
                    AuthorizationMiddleware::class
                ]
            ]
```

**Comment by weierophinney** [comment]
That's something you can do with nested middleware applications.

As an example, you can have pipeline middleware that checks against the host, and then dispatches another Expressive application based on the match:

```php
$host = $request->getHeaderLine('Host');

switch (strtolower($host)) {
    case 'api':
        $api = $this->container->get('ApiApplication');
        return $api($request, response, $next);
    default:
        return $next($request, $response);
}
```

Just a quick point of clarification: the path-based matching in pipeline middleware is a feature of Stratigility, which inherits the feature from Sencha Connect. Its primary purpose is path-based segregation; if you want to do host-based segregation, you either run the application on a separate host, or you use a solution like I outline above.

**Comment by bakura10** [comment]
Sounds like a nice solution. But maybe Stratigility implementation could deviate a bit to add this feature? That sounds like a pretty simple feature, as today in Expressive there is basically no easy way through config to perform routing based on host.

**Comment by weierophinney** [comment]
@bakura10 I don't want to bloat Stratigility too much, but that should be relatively easy to add. Want to contribute a PR?

**Comment by bakura10** [comment]
Yep will try to do that when I have a bit of time :).

**Comment by artwis** [comment]
Hey, has anyone worked on this feature? If not I'd be willing to submit PRs to Stratigility and Expressive to allow host based middleware pipe routing.

**Comment by webimpress** [comment]
It's possible now with Expressive 3. See:
- https://github.com/zendframework/zend-stratigility/pull/142
- https://docs.zendframework.com/zend-stratigility/v3/api/#host
