### ISSUE TITLE
How to redirect to a given middleware?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#236]
Hi,

@weierophinney this is the issue I was talking about on Twitter, but maybe it is better here.

I want to create a middleware that is used with Elastic Beanstalk SQS worker. Elastic Beanstalk is an AWS service that allows to deploy applications easily, and they also have an environment type called "worker".

This type of environment fetches messages from a SQS queue, and then does a POST request to a URL of our choice in our application, with the message info.

What I'd like to do is creating a small abstraction layer around this, so that I can push messages in my application:

```php
$queue->push('my-job-name', ['user_id' => 2, 'other-info' => 'bar']);
```

Once read by the worker, it can be configured to do a POST to "/worker" URL for instance.

My idea is that I'd like to use a mapping between the name of the job, to a given middleware. Therefore, I'd like to be able to create a "WorkerMiddleware" (that will be configured on the path I've configured Elastic Beanstalk), and that this middleware would read the "job name" (in my example "my-job-name"), and match it to a middleware, and then automatically dispatch to this middleware.

I have thought of two solutions:

## Inject the container

The first idea is to inject the container inside this middleware, so I can retrieve the dependant middleware and call it (or add it to the pipe ?).

## Pre-routing

The other idea I had is to add a pre-routing middleware that will dynamically change the request path, so that when the "routes" are fetched, it will actually dispatch to the proper middleware.

Is there any other solution for this problem? (yes, I'm basically looking for something similar to the ->forward() controller helper we had in ZF1 :o)

**Comment by weierophinney** [comment]
The first is definitely the easiest; essentially, you're just creating an alternate routing middleware that uses the POST data for routing instead of using path-based routing. As far as I'm concerned, that's likely the simplest and best solution.

The second option is also viable, and quite reasonable to do as pre-routing middleware.

Honestly, take your pick; they're both reasonable solutions.

**Comment by bakura10** [comment]
Perfect, I'll go with the first one then.

**Comment by SlayerBirden** [comment]
To whoever's searching - there's a `\Zend\Diactoros\Response\RedirectResponse` specifically for redirecting purpose.
