### ISSUE TITLE
Use Foo::class instead of 'Foo'

### ISSUE THREAD

**Issue by yourwebmaker** [zendframework/zend-expressive#245]
I just took a look into the project and it seems very promissor. :+1: 

https://github.com/zendframework/zend-expressive/blob/master/test/AppFactoryTest.php#L32

No more explanations. The issue title talks by itself. Can we do that?

Thanks guys.

**Comment by bakura10** [comment]
Sure, that would be good, especially for refactoring a class name, at least with ::class those are automatically updated. Can you do a PR? :)

**Comment by Maks3w** [comment]
I would prefer if this kind of checks could be automated and fixed by some tool.

**Comment by weierophinney** [comment]
Closed with #246.
