### ISSUE TITLE
FlahsMessenger for Zend\Expressive

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive#248]
Like described here: https://github.com/zendframework/zend-mvc/issues/52

I would like to use someting like the `FlashMessenger` within my `Zend\Expressive` application without the need of installing the whole `Zend\Mvc` package.

**Comment by xtreamwayz** [comment]
Something like this?

https://github.com/slimphp/Slim-Flash

**Comment by RalfEggert** [comment]
Then I would rather prefer the original `FlashMessenger` because it supports different message namespaces. 

Currently to pass a message from one middleware to the next middleware in the pipe I used a request attribute. But that won't work for a real redirect.

**Comment by weierophinney** [comment]
This would indeed be a useful feature. I wonder if it could be built-in to Ocramius/PSR7Session, as I'm likely to direct folks to that library for session management with expressive ... (pinging @Ocramius )

**Comment by dannym87** [comment]
@weierophinney I've built a little middleware library that uses Aura Session. Any feedback is much appreciated https://github.com/dannym87/expressive-session-middleware

**Comment by basz** [comment]
@dannym87 have a look at https://github.com/oscarotero/psr7-middlewares/blob/master/src/Middleware/AuraSession.php

**Comment by samsonasik** [comment]
@RalfEggert @dannym87 I give a try create cookbook pr #306 for it
