### ISSUE TITLE
Documentation parsing is broken?

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zend-expressive#256]
The code blocks show the language type on the pages. 

On page [this page](https://zend-expressive.readthedocs.org/en/latest/usage-examples/#using-the-built-in-web-server) it shows:

bash
$ php -S 0.0.0.0:8080 -t public

It should be:

```bash
$ php -S 0.0.0.0:8080 -t public
```

This happens on multiple pages. I have checked the markdown files and they seem to be fine. Also locally compiling the docs is ok.

**Comment by weierophinney** [comment]
It's a limitation of the markdown library used on rtfd.org; it doesn't
support fenced blocks that are part of list items (github and
league/markdown do, however). It's a non-issue as far as I'm concerned;
rtfd is a temporary location.
