### ISSUE TITLE
add more "/" in route get 405 Method Not Allowed error

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive#257]
I tried to use zend-expressive-skeleton, apply url `/api/ping/` ( more "/" in url ) and got get 405 Method Not Allowed error. Here is the screnshot:

![screen shot 2016-01-02 at 4 36 42 am](https://cloud.githubusercontent.com/assets/459648/12072305/c530135e-b10a-11e5-8b84-c5cde3ae4499.png)
while if it means route not found, should be get 404 page.

**Comment by samsonasik** [comment]
for setup to reproduce:

```
Minimal skeleton? (no default middleware, templates, or assets; configuration only)
  [y] Yes (minimal)
  [n] No (full; recommended)
  Make your selection (No): 

  Which router do you want to use?
  [1] Aura.Router
  [2] FastRoute
  [3] Zend Router
  Make your selection or type a composer package name and version (FastRoute): 3
  - Adding package zendframework/zend-expressive-zendrouter (^1.0)
  - Copying /config/autoload/routes.global.php

  Which container do you want to use for dependency injection?
  [1] Aura.Di
  [2] Pimple
  [3] Zend ServiceManager
  Make your selection or type a composer package name and version (Zend ServiceManager): 3
  - Adding package zendframework/zend-servicemanager (^2.5)
  - Adding package ocramius/proxy-manager (^1.0)
  - Copying /config/container.php

  Which template engine do you want to use?
  [1] Plates
  [2] Twig
  [3] Zend View installs Zend ServiceManager
  [n] None of the above
  Make your selection or type a composer package name and version (n): 3
  - Adding package zendframework/zend-expressive-zendviewrenderer (^1.0)
  - Copying /config/autoload/templates.global.php
  - Copying /templates/error/404.phtml
  - Copying /templates/error/error.phtml
  - Copying /templates/layout/default.phtml
  - Copying /templates/app/home-page.phtml

  Which error handler do you want to use during development?
  [1] Whoops
  [n] None of the above
  Make your selection or type a composer package name and version (Whoops): 1
```

and then, access http://localhost:8080/api/ping/

**Comment by RalfEggert** [comment]
In that scenario you can access one page with two different URL, one with the slash at the end and one without it. AFAIR, search engines will count this as two different pages, so in general this should be avoided.

To fix it I just add a quick rewrite rule to my .htaccess to solve this:

```
# Remove slash from end
RewriteEngine  on
RewriteRule ^(.+)/$ http://%{HTTP_HOST}/$1 [R=301,L]
```

Another idea would be to write a small `pre_routing` middleware which does a redirect if the URL ends with a slash and does not contain the slash as the only char (for the homepage).

**Comment by xtreamwayz** [comment]
As long as the content is the same for both url's you can serve with and without the backslash. But it's better to use only one and redirect: https://googlewebmastercentral.blogspot.com.es/2010/04/to-slash-or-not-to-slash.html

But yes I agree this should be a 404 error and not a 405. I have tried the same with FastRoute and Aura.Router and they show a 404 as expected. So I guess it's an issue with zend-router.

**Comment by samsonasik** [comment]
Yes, the issue is it should be 404 insteaf of 405

**Comment by weierophinney** [comment]
@samsonasik I'm assuming you're using the skeleton with no modifications to the routes?

As such, please open an issue against zend-expressive-zendrouter, as the issue lies either in that bridge implementation, or in the zend-mvc router, and needs to be addressed in one of those two locations.

From what I can see, it looks like either the zend-mvc router is matching incorrectly, or the return value from matching is a failure, but we're interpreting it incorrectly. Either way, it's in a different repo.

**Comment by samsonasik** [comment]
I've created issue in https://github.com/zendframework/zend-expressive-zendrouter/issues/3
