### ISSUE TITLE
PHP 7 exceptions not supported

### ISSUE THREAD

**Issue by penegiryk** [zendframework/zend-expressive#288]
In PHP 7 some errors that were previously fatal are now catchable exceptions (e.g. parse error).
Expressive doesn't support this new type of exceptions because it typehints exceptions to \Exception. 

As a result, when using Whoops (which is now in stable 2.0 version and support php 7) and \Error exception is raised, the result is blank page.

I think changes in Stratigility are also necessary to fix this.

**Comment by weierophinney** [comment]
We don't actually want to catch engine errors; those should be handled entirely separately. We're only interested in catching userland errors.

**Comment by penegiryk** [comment]
This also affects exceptions like TypeError which is thrown quite often when developing php 7 application. Whoops handles this exception but result is not rendered and blank page is shown. Because whoops registers exception handler, error handler and shutdown handler, there is no indication to what happened (blank page). It makes Whoops unusable because on every blank page you have to switch to different error handler to see what's wrong.

**Comment by Ocramius** [comment]
Agree with @penegiryk here. Worked a bit with strict types and return types, and a misplaced type currently causes the entire thing to blow up with no output (actually seems to still run till the `FinalHandler`, instead of crashing). This makes it a major pain-point when working with a PHP7+expressive app...

**Comment by weierophinney** [comment]
Thanks for the feedback and use cases, @penegiryk and @Ocramius ! This is indeed something that needs to be handled in Stratigility; the try/catch block is in the `Dispatch` class of that library. Please open an issue / patch on that project.

**Comment by penegiryk** [comment]
I see there is already a waiting pull request on Stratigility side:
https://github.com/zendframework/zend-stratigility/pull/37

Changes in Expressive are also needed to fix this, currently TemplatedErrorHandler passes \Error exceptions to handleError method instead of handleException.

**Comment by penegiryk** [comment]
@weierophinney I created a pull request which fixes this on Expressive side, but the above pull request to Stratigility is also needed to be merged for this to work.
