### ISSUE TITLE
How switch from zf2 to expressive

### ISSUE THREAD

**Issue by webdevv** [zendframework/zend-expressive#292]
Hi. How can I switch from zf2 to expressive, while maintaining a modular system and using all the features of the zf2?

**Comment by weierophinney** [comment]
We're working on an Expressive wrapper for ZF2 at this time, but do not have a scheduled date for completion. That wrapper will mainly allow you to expose an existing ZF2 application within an Expressive install, and the migration path would then be to gradually rewrite your controllers as middleware, and attach them directly to the Expressive application.

In the meantime, you can already use any ZF2 components you want within an Expressive application, just by requiring them via composer:

```console
$ composer require zendframework/zend-<component>
```

This will add it to your list of requirements and install it. Once you have, you can make use of it immediately. In some cases, you may need to expose factories or abstract factories; you can do that within your dependencies configuration. In some cases, in ZF2, we auto-register some configuration for plugin managers which you'll need to duplicate in your Expressive application; we [demonstrate one such case with form view helpers](http://zendframework.github.io/zend-expressive/cookbook/using-zend-form-view-helpers) in the documentation already.

In terms of modularity, we already have a [cookbook recipe covering modular applications](http://zendframework.github.io/zend-expressive/cookbook/modular-layout/); we will likely make this either an option or the default in the skeleton with 1.1.
