### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive#310]
As far as I remember, the 1.1.0 release will integrate https://github.com/mtymek/expressive-config-manager to provide a modular structure for `Zend\Expressive` apps. 

I know there is a lot to do currently and it will be hard to tell. But are there any release plans for 1.1.0 yet? Will it come shortly or only in a couple of months? Will it come before the ZF3 release or after it? 

I just wonder if I should add the modular layout from the cookbook already to be future-proof or if the recommended modular structure for 1.1.0 will be much different than in the cookbook?

http://zend-expressive.readthedocs.org/en/latest/cookbook/modular-layout/

**Comment by xtreamwayz** [comment]
I've made a proposal for the config manager a while ago: zendframework/zend-expressive-skeleton#54
It still needs a review, the creation of zendframework/zend-expressive-config-manager and some decisions about pushing a module structure and how it exactly should look like (where to place config files, templates, etc).

**Comment by xtreamwayz** [comment]
Also, the proper link for the docs is on the github pages: https://zendframework.github.io/zend-expressive/cookbook/modular-layout/

That modular layout is for the config only actually. It doesn't have a recommendation on the module structure and where to place files like templates. There has been a lot of discussions about a modular structure in several places, but I can't remember a final decision has been made yet.

**Comment by RalfEggert** [comment]
Here is a discussion about the structure with a practical suggestion:

https://github.com/zendframework/zend-expressive/issues/176#issuecomment-160106303

**Comment by xtreamwayz** [comment]
I know, but those are suggestions. There is no final decision made yet on what version to use for the skeleton, or maybe even leave it as it is now.

**Comment by RalfEggert** [comment]
I posted the link to the discussion because that was the one I remember. I know that no decision has been made yet.

**Comment by mtymek** [comment]
I think this should be a part of discussion around Skeleton application, not Zend Expressive itself. I see this cookbook is pretty future-proof - I don't expect too many changes besides adding notes like "If you are using Expressive Skeleton, config manager is installed by default", or updating repository URL.

**Comment by glen-84** [comment]
Will 1.1 be released once the skeleton is ready (https://github.com/zendframework/zend-expressive-skeleton/pull/124)?

**Comment by weierophinney** [comment]
@glen-84 there's a few other pieces we're waiting on, one of which is updating Stratigility to cover the 0.4.1 release of http-interop/http-middleware, which changes the namespace, several interface names, and removes the client-related functionality. As such, it's still likely a couple weeks out.

**Comment by weierophinney** [comment]
The modular structure is incorporated in the upcoming zend-expressive-skeleton 2.0 release (via zendframework/zend-expressive-skeleton#54).
