### ISSUE TITLE
Smarty templating support for ZF expressive.

### ISSUE THREAD

**Issue by webdesign7** [zendframework/zend-expressive#311]
Hello 

I know there is support for various template engines ( Twig, Plates etc ) but as you know :) always is not enough  .. is there any support for Smarty template engine and if not any plans to be supported in your future releases ? By the way I tried to install smarty through composer and I got all sort of nasty errors. 

Can you please shed some light on this ? 

Cheers
Sergiu C.

**Comment by Ocramius** [comment]
> By the way I tried to install smarty through composer and I got all sort of nasty errors. 

What kind of nasty errors? Did you report them to the smarty developers at https://github.com/smarty-php/smarty/issues ?

**Comment by webdesign7** [comment]
well.. I think those errors are rather related to ZF expressive composer.json dependencies.

![errors](https://cloud.githubusercontent.com/assets/2030016/12785390/4565deb8-ca84-11e5-98a4-26e523b28d35.jpg)

**Comment by Ocramius** [comment]
Those errors (not actual errors, your dependencies are simply incompatible) are unrelated to smarty and expressive: please check your `composer.json` dependencies.

Closing here, as it is an issue not related to expressive itself.

**Comment by harikt** [comment]
@webdesign7 probably show your composer.json so may be we can help you with. Regarding smarty template engine support, you could actually make use of https://github.com/zendframework/zend-expressive-template and smarty to build a separate package. See https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/src/TwigRenderer.php as  a starting example.

You only need to implement this https://github.com/zendframework/zend-expressive-template/blob/master/src/TemplateRendererInterface.php .

Hope that helps you to build one yourself.

Thank you.

**Comment by webdesign7** [comment]
@Ocramius I wouldn't say that the problem is in my composer dependencies as I all I do is download a fresh copy  through composer  and then going and require additional libraries through composer .. you probably want to give it a go yourself  and also just FYI I tried to download other composer packages ( like Zend-DB for instance )  and it didn't go through as well.  I don't mind you can close the ticket however I think you might need to tweak your composer.json a little .. I believe  there would be other similar requests in the future. 
Regards

**Comment by webdesign7** [comment]
@harikt thanks!  good answer ! it all makes sense  and that's what I expected , just wanted to double check.

**Comment by xtreamwayz** [comment]
> I wouldn't say that the problem is in my composer dependencies as I all I do is download a fresh copy through composer and then going and require additional libraries through composer.

That last part is precisely what ocramius was telling you. You are adding other dependencies which are incompatible with the ones already exist. e.g. If you have zend-servicemanager 3 as a dependency and try to add a zendframework package that is not yet ready for zf3 and needs zend-servicemager 2.x it can't install the dependency. You need to stick to zf2 components only in that case.
