### ISSUE TITLE
Custom dispatch middleware, default route middleware, and route attributes

### ISSUE THREAD

**Issue by glen-84** [zendframework/zend-expressive#312]
I created a [BaseControllerTrait](http://pastie.org/private/hutorg7doqvlicwmwqpw), and I was wondering whether to instead extend a base class, so I went onto `##php` to ask for opinions. The feedback was a bit mixed, but a somewhat-unrelated suggestion was made that I move the `__invoke` code (dispatch & automatic template rendering) to a separate middleware class. This makes sense to me, but I'm a bit unsure as to how to accomplish it.

I was thinking of something along these lines:

``` php
    'routes' => [
        [
            'name' => 'app.site',
            'path' => '/[{action}]',
            'middleware' => My\Dispatch\Middleware::class,
            'allowed_methods' => ['GET']
        ]
    ]
```

However:

`1.` If the controller is not part of the route, how do I send that information to the dispatch middleware? I thought that maybe an `attributes` key could be added to the route interface, so you'd do:

``` php
    'routes' => [
        [
            'name' => 'app.site',
            'path' => '/[{action}]',
            'middleware' => My\Dispatch\Middleware::class,
            'allowed_methods' => ['GET'],
            'attributes' => [
                'controller' => My\Controller\Class::class,
                'somethingElseLikeADefaultAction' => '...'
            ]
        ]
```

Which would then be available via the request.

`2.` Specifying the same middleware over and over could get annoying, so it would be nice if you could specify default middleware to use if the route doesn't specify any.

 `3.` I'm not sure how this relates to `ApplicationFactory::DISPATCH_MIDDLEWARE`? Does it replace it, come before/after it, etc.

This is just an idea – I wanted to get feedback in case I was thinking of doing something silly when there may be better options.

Your thoughts?

**Comment by xtreamwayz** [comment]
One way to do it would be with zend-servicemanager and an [abstract factory](http://zendframework.github.io/zend-servicemanager/configuring-the-service-manager/#abstract-factories). That way you have a factory that you can reuse to inject all the common dependencies.

However when you have extra dependencies like service classes, data storage, etc you need to write custom factories or you can use reflection to detect what to inject: https://xtreamwayz.com/blog/2015-12-30-psr7-abstract-action-factory-one-for-all

**Comment by glen-84** [comment]
@xtreamwayz I'm already using an abstract factory similar to yours to construct the controllers (we discussed this a few days ago on `#zftalk.dev` [my nick there is `darkangel`]).

However, this issue is about how to introduce a custom dispatcher so that this code can be separated from the controller class.

**Comment by jkhaled** [comment]
you can create a middleware  playing role of dispatcher  and pipe it to be executed after the routingMiddleware and check if request(path) match what you desire then return the specific middlewareAction.

**Comment by glen-84** [comment]
@jkhaled How would the dispatch middleware know which controller to load? I need to pass the controller name from the route configuration. For this I need to be able to specify `attributes` (or similar).

**Comment by codeliner** [comment]
@glen-84 When using the AuraRouter you can assign values to each route which are then added to the request attributes. See this [example config](https://github.com/prooph/proophessor-do/blob/master/config/routes.php#L59)

**Comment by glen-84** [comment]
@codeliner Interesting; however, I'd like this to work regardless of which router implementation is chosen. Route options are specific to each implementation.

**Comment by weierophinney** [comment]
Closing, as this thread contains no actionable items currently.
