### ISSUE TITLE
How i can develop console cli commands?

### ISSUE THREAD

**Issue by maxgu** [zendframework/zend-expressive#313]
Now i dont see ConsoleResponse. And `php public/index.php` output raw html.
How i can do this?

**Comment by xtreamwayz** [comment]
I actually got this working yesterday with [symfony console](http://symfony.com/doc/current/cookbook/console/console_command.html).

```php
<?php // app.php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

/** @var \Interop\Container\ContainerInterface $container */
$container = require __DIR__ . '/config/container.php';
$application = new Application('Application console');

$commands = $container->get('config')['console']['commands'];
foreach ($commands as $command) {
    $application->add($container->get($command));
}

$application->run();
```

```php
<?php // config/autoload/console.global.php

return [
    'dependencies' => [
        'invokables' => [
        ],

        'factories' => [
            App\Command\MyCommand::class => App\Command\MyCommandFactory::class,
        ],
    ],

    'console' => [
        'commands' => [
            App\Command\MyCommand::class,
        ],
    ],
];
```

**Comment by xtreamwayz** [comment]
In case you want an example: https://xtreamwayz.com/blog/2016-02-07-zend-expressive-console-cli-commands

**Comment by weierophinney** [comment]
Expressive utilizes PSR-7 middleware, which is specifically for *HTTP*. As such, it cannot handle request/response pairs for console applications. 

To be honest, I was never comfortable with having zend-mvc handling console requests. The capabilities of http and console requests and responses are quite different, which means that you cannot realistically use the same action method to handle either type, at least not without a lot of branching. For this reason, we created [zfcampus/zf-console] (https://github.com/zfcampus/zf-console); with it, you create dedicated console applications that you can have live within your existing application, but which do not use http facilities, and target side specifically console capabilities. You can reuse your service definitions easily, giving you access to the logic you write for your domain, but with a clean separation of concerns with regards to the environment.

[My own site does this] (https://github.com/weierophinney/mwop.net); browse in the bin/ directory for the mwop.net command. I strongly recommend the approach.

**Comment by maxgu** [comment]
I agree. HTTP request handling and Console command - it's two different app.
[bin/mwop.net.php](https://github.com/weierophinney/mwop.net/blob/master/bin/mwop.net.php) - great example, thnx.
