### ISSUE TITLE
How i can run middleware after dispatching Action?

### ISSUE THREAD

**Issue by maxgu** [zendframework/zend-expressive#316]
For example: i have over 20 Actions, which return `HtmlResponse` \ `JsonResponse`. And now i want log json output. How i can do this?

Edit\Update all Actions? 
And remove `return new JsonResponse($data);`?

**Comment by mtymek** [comment]
You can take advantage of "onion" style middleware in Expressive - solution to your problem can look like this:

```php
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)
{
    $response = $next($request, $response);

    if ($response instanceof \Zend\Diactoros\Response\JsonResponse) {
        // ... log JSON here
    }
    
    return $response;
}
```

This middleware should be registered with high priority (so that it will be always executed.

**Comment by maxgu** [comment]
thnx, work :)
