### ISSUE TITLE
How i can change layout from not Action middleware?

### ISSUE THREAD

**Issue by maxgu** [zendframework/zend-expressive#317]
I want set admin layout if /admin/\* uri:

``` php
if (strpos($request->getUri()->getPath(), '/login') !== false) {
    // change layout
}

return $next($request, $response);
```

How i can change layout?

**Comment by jkhaled** [comment]
can you precise wish template-render you are using because  they behave different (plates, zend-view, twig)

**Comment by maxgu** [comment]
i use Zend\View

**Comment by djozsef** [comment]
See this issue. https://github.com/zendframework/zend-expressive-skeleton/issues/68 

TL;DR
Pass a "layout" key with the layout path to the view renderer
