### ISSUE TITLE
Fix the github repo description/strapline

### ISSUE THREAD

**Issue by Thinkscape** [zendframework/zend-expressive#333]
Currently the strapline is: 
## ![image](https://cloud.githubusercontent.com/assets/270528/14277118/095bea42-fb22-11e5-8e4e-5ef7528fddb8.png)

I believe it's supposed to be the same as in readme.md

> Develop PSR-7 middleware applications in minutes!

**Comment by i-am-tom** [comment]
To spot another one: the text under the `h1` says "PSR-7 Middleware in Minutes" on https://zendframework.github.io/zend-expressive/. Happy to PR if this would be a "branding fix"!

**Comment by weierophinney** [comment]
Updated; thanks!
