### ISSUE TITLE
[Cookbook] Zend\Form view helpers

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive#335]
Since the `Zend\Form\View\HelperConfig` is deprecated with release 2.8.0 of `Zend\Form`, how could this recipe be updated? I guess the new Config-Provider should be used, but how?

https://zendframework.github.io/zend-expressive/cookbook/using-zend-form-view-helpers/

**Comment by weierophinney** [comment]
@RalfEggert for the 1.1 release of the skeleton, we'll be baking in the expressive-config-manager (likely as zend-config-manager or similar), and zend-component-installer. Once that's done, the recipe becomes "install zendframework/zend-form", and it's taken care of.

Until then, we can recommend creating a file `config/autoload/zend-form.global.php` with the contents:

```php
<?php
use Zend\Form\ConfigProvider;

$provider = new ConfigProvider();
return $provider();
```

and that will essentially do everything needed.
