### ISSUE TITLE
How to get route result in action factory?

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-expressive#337]
I am trying to create CRUD application using zend-expressive. My idea is to have default crud routes and if some entity needs non-default dependencies, it could be overriden.

```
'routes' => [
    'crud.add' => [ // default entites have default factory
        'name' => 'crud.add',
        'path' => '/crud/:entity/add',
        'middleware' => App\Action\CrudAddAction::class,
        'allowed_methods' => ['GET', 'POST'],
    ],
    'crud.add.article' => [ // articles have own factory
        'name' => 'crud.add.article',
        'path' => '/crud/article/add',
        'middleware' => App\Action\ArticleAddAction::class,
        'allowed_methods' => ['GET', 'POST'],
    ],       
],
```

And the problem is, how could I grab entity name (from route result) in default action factory? If I have entity name I can get dependencies from container and inject them into CrudAddAction constructor.

**Comment by xtreamwayz** [comment]
I don't think this is possible without hacking expressive. The RouteResult is not available in the factory. You can get it only from the request. Solutions I can think of:

1. Hack the expressive-router, store the RouteResult in the match method and add a getRouteResult method to retrieve it.
2. Retrieve the RouteResult from the [URLHelper](https://github.com/zendframework/zend-expressive-helpers/blob/master/src/UrlHelper.php#L129), but you need to override that class and make getRouteResult() a public method.
3. (really really bad solution) Inject the container inside the default action and get the dependencies there. No hacking required.

Maybe there are better solutions, but if not I would go for option 2.

**Comment by vaclavvanik** [comment]
@xtreamwayz thx for your points. I have same opinion that option 2 is the best one.

**Comment by danizord** [comment]
I'd go with option 3, it is not so bad if you test it properly, and it's way better than relying on stateful service (option 2). Also, make sure to handle ServiceNotFound exception case. :)

**Comment by vaclavvanik** [comment]
@danizord option 3 is practically deprecated ServiceLocatorAwareInterface.
@xtreamwayz and option 4 - to create smth like RouteResultHelper and its middleware (simplified copy of UrlHelper). Done without inheriting UrlHelper.

Question is - how much cool is to rely on stateful service as @danizord mentioned.

**Comment by Ocramius** [comment]
Please do not do this: factories are pre-dispatch context, they do not know anything at all about the current request, and that for good reasons. If you need to build something aware of the current request, then make sure it is used and garbage-collected inside the action itself.

```php
final class RouteRepositoryResolver implements RouteRepositoryResolverInterface
{
    public function getRepositoryFor(RouteResult $routingResult) : RepositoryInterface
    {
        // take decisions here...
    }
}
```

```php
final class CrudPostFactory
{
    public function __invoke(ContainerInterface $container)
    {
         return new CrudPost($container->get(RouteRepositoryResolver::class)
    }
}
```

Now you can use `CrudPost` for any route:

```php
'routes' => [
    'crud.list' => [
        'name' => 'crud.list',
        'path' => '/crud/:entity',
        'middleware' => CrudList::class,
        'allowed_methods' => ['GET'],
    ],
    'crud.get' => [
        'name' => 'crud.get',
        'path' => '/crud/:entity/:id',
        'middleware' => CrudGet::class,
        'allowed_methods' => ['GET'],
    ],
    'crud.post' => [
        'name' => 'crud.add',
        'path' => '/crud/:entity',
        'middleware' => CrudPost::class,
        'allowed_methods' => ['POST'],
    ],
    'crud.delete' => [
        'name' => 'crud.remove',
        'path' => '/crud/:entity',
        'middleware' => CrudPost::class,
        'allowed_methods' => ['DELETE'],
    ],
],
```

Your `RouteRepositoryResolverInterface` is responsible for fetching the right repository (and may actually use the service locator, in this **very specific** case).

**Comment by edigu** [comment]
@Ocramius here is another specific case;

I have a `EntityManagerFactory` ending with the following lines;

```php
        // ... bunch of configuration lines..
        $evm->addEventSubscriber($translator);
        $evm->addEventSubscriber(new TimestampableListener());
        $evm->addEventSubscriber(new IpTraceableListener());
        return EntityManager::create($conf['connection']['orm_default'], $config, $evm);
```

and I need to pass the user's IP address from request to `IpTraceableListener` like:

```php
$listener = new IpTraceableListener();
$ip = $request->getAttribute('user_ip');
$listener->setIpValue($ip);
$evm->addEventSubscriber($listener);
```

I also have a `RealIPMiddleware` which resolves remote ip address and appends it to the current request:

```php
class RealIPMiddleware
{
    public function __invoke(Request $request, Response $response, callable $next)
    {
        $request = $request->withAttribute('user_ip', $this->resolveIP($request));
        return $next($request, $response);
    }
```

I truly understand the pre-dispatch context of the factories however i'm looking for a nice (or correct) way to do this. What is your suggestion?
