### ISSUE TITLE
Invokable error handler question

### ISSUE THREAD

**Issue by n3vrax** [zendframework/zend-expressive#338]
Hi,

I was trying to register a error handler like this 

``` php
'error' => [
            'middleware' => [
                // Add error middleware here.
                \App\ErrorHandler\Unauthorized::class,
            ],
            'error'    => true,
            'priority' => -10000,
        ],
```

The error handler class is a no dependency constructor, so I haven't registered it as a invokable service. I thought the Application factory will parse the middleware_pipeline and instantiate them, and as much as I can follow the code, it should work this way(reached the `marshalInvokableMiddleware` method)

The problem is that it's not working. If I register it in the dependencies section too, it works, otherwise it looks like it skips, and reaches the final handler. Am I missing something?

The error handler class looks like this

``` php
class Unauthorized
{
    public function __invoke(
        $error,
        ServerRequestInterface $request,
        ResponseInterface $response,
        callable $next = null
    )
    {
        //this is just prototyping to test it, it will be included in a separate auth package
        if($error instanceof AuthenticationError)
        {
            if($error->getCode() === 401 || $response->getStatusCode() === 401) {
                //redirect to login
                return new RedirectResponse('http://localhost:8080/login');
            }
        }
    }
```

Thanks!

**Comment by xtreamwayz** [comment]
The code looks alright and it should be working without adding it as a dependency. I know it doesn't help much, but that code works for me.

**Comment by syaiful6** [comment]
i can confirm it also happen to me, i try to var_dump the error handler and it printed to browser, so it reached my error handler, but i dont know why it still reached to final handler, hmmm.

```

    public function __invoke($error, Request $request, Response $response, callable $next = null)
    {
        if ($error instanceof TokenMismatchException) {
            $html = $this->template->render('error::csrf403', [
                'title' => 'Forbidden',
                'main'  => 'CSRF verification failed. Request aborted.'
            ]);
            $stream = new Stream('php://memory', 'wb+');
            $stream->write($html);
            var_dump('reached?');
            return $response
                ->withBody($stream)
                ->withStatus(403, 'Forbidden')
                ->withHeader('Content-Type', 'text/html');
        }

        return $next($request, $response, $error);
    }
```

![screenshot 70](https://cloud.githubusercontent.com/assets/2830977/15421114/b7a89540-1e9b-11e6-9d1d-c9b6a9230b8f.png)

**Comment by syaiful6** [comment]
hmm, my bad. In my case it look like one of my middleware not return the something. So, it work now. :)
