### ISSUE TITLE
Change UrlHelper getBasePath() visibility to public

### ISSUE THREAD

**Issue by jkiefmann** [zendframework/zend-expressive#341]
It would be nice if the Method Zend\Expressive\Helper\UrlHelper::getBasePath would be public. At the moment it's protected.

A method like addBasePath() would be even better, so if there is already a basePath set, the new path will be appended.

**Comment by froschdesign** [comment]
@jkiefmann 
This is the wrong issue tracker. Use [zendframework/zend-expressive-helpers](https://github.com/zendframework/zend-expressive-helpers/issues).

But the helper has already the methods [`setBasePath`](https://github.com/zendframework/zend-expressive-helpers/blob/master/src/UrlHelper.php#L112) and [`getBasePath`](https://github.com/zendframework/zend-expressive-helpers/blob/master/src/UrlHelper.php#L139).

**Comment by jkiefmann** [comment]
I know that there is a getBasePath Method, but the Problem is it's protected.

I've created a new issue here [https://github.com/zendframework/zend-expressive-helpers/issues/13](https://github.com/zendframework/zend-expressive-helpers/issues/13).
