### ISSUE TITLE
Why not to name AppFactory -> ApplicationFactory?

### ISSUE THREAD

**Issue by nuclearhead** [zendframework/zend-expressive#345]
Hello,
I was wondering why there is a name Zend\Expressive\AppFactory for Application class object creation. I know there is already Zend\Expressive\Container\ApplicationFactory but we have namespaces to distinguish those two right? 

So I would like to name AppFactory -> ApplicationFactory, maybe it's not important detail but for me it's confusing and against already used naming convention. But I want to know your opinions before making any pull request.

**Comment by xtreamwayz** [comment]
The AppFactory is being used for stand alone usage and the ApplicationFactory is used by containers. They both return the Application.

The only reason I can find is it is named after the variable it's [stored in](https://zendframework.github.io/zend-expressive/getting-started/standalone/#4-create-your-bootstrap-script): 
```php
$app = AppFactory::create();
```

I'm not sure if renaming it to ApplicationFactory makes it any clearer. You will than have two of those classes and might cause more confusion. Although the `Container` namespace might give a hint, I doubt everyone will get it. If you have two different class names, people need to think and read which one to use.

Merging the two might be an option as well. They have the same result. However for consistency it makes more sense to keep them separate and have one inside the Container namespace.

If this is going to be changed, it's going to be a BC break. Meaning the AppFactory must be deprecated first and in the far far future it should be removed in version 2.0.

**Comment by ezimuel** [comment]
@nuclearhead the `Zend\Expressive\AppFactory` and `Zend\Expressive\Container\ApplicationFactory` are two different factory classes used for different scopes. 

The first is used to create (from a static call) an `Zend\Expressive\Application` instance passing 2 optional parameters: `ContainerInterface` and `Router\RouterInterface`). 

The second is used to return a `Zend\Expressive\Application` in a Container scenario and it requires a non optional `ContainerInterface` parameter).

I think it will be more confusing to have just one factory to operate in two different scenarios.

**Comment by nuclearhead** [comment]
> people need to think and read which one to use
Yes, generally programming is based on thinking :dancer: 

> You will than have two of those classes and might cause more confusion
I think this is opinion only. For me - more confusion brings inconsistency in naming convention than that I should not think what I am doing with code. ;-)

Ok, I don't want to make storm because of this. Thanks for explanations about the reason why not to rename it now. I think BC is the strongest reason here and the only one.

**Comment by nuclearhead** [comment]
To @ezimuel 
> I think it will be more confusing to have just one factory to operate in two different scenarios.

I agree, for me there was only option for renaming class.

For me it's only about naming standards and not what is confusing. The same naming as for AppFactory we could use for every class so against ErrorMiddlewarePipe we can use ErrMiddlewarePipe etc. but in my opinion it's against convention.

If you would like to use both classes in the same file (I think it's really rare use case?) you can make it very clear:
`
use Zend\Expressive;

$containerBasedApplicationFactory = new Container\ApplicationFactory;
$generalApplicationFactory = new ApplicationFactory;
`
