### ISSUE TITLE
Check for exististence of ZendServiceManager before trying to instantiate it.

### ISSUE THREAD

**Issue by dantleech** [zendframework/zend-expressive#352]
Currently the `AppFactory` will try and instantiate the `ZendServivceManager` by default if no container is given, causing a Fatal Error if that class is not present.

As the package depends on no container implementation, would it not make sense to have no default?

(same applies to FastRoute)

**Comment by xtreamwayz** [comment]
You need at least a container and router to get Expressive working. If you use the installer those options are the only two forced, everything else is optional. If you don't use the installer, you have to supply those yourself.

The package doesn't rely on a *specific* container or router implementation, but it does rely on `ContainerInterface` and `RouterInterface`.

Thinking about it, it would make sense to remove `= null` and enforce a container and router in the constructor in AppFactory. Same would be for throwing an exception if a `RouterInterface` is not found in the container in `Container\ApplicationFactory`. A container is already required there.

**Comment by dantleech** [comment]
> Thinking about it, it would make sense to remove = null and enforce a container and router

+1 think it would also make it more obvious how it is working by expicitly injecting the container.

**Comment by weierophinney** [comment]
This would, however, be a backwards incompatible change, as it makes a previously optional parameter required.

What we _can_ do now is raise an exception if no container or router is provided, and neither of the defaults are available. This would be completely backwards compatible.
