### ISSUE TITLE
Cannot use multiple error middleware

### ISSUE THREAD

**Issue by cottton** [zendframework/zend-expressive#355]
see also https://github.com/zendframework/zend-expressive/issues/264 imo not solved.

I found out also that multiply error middleware does not get invoked.
config:

	[
	    'middleware' => [
	    	// this should be the first one
	        App\Error\ErrorMiddleware::class, 
	    ],
	    'error'      => true, 
	    'priority'   => PHP_INT_MAX, // always first
	],
	[
	    'middleware' => [
	    	// this should be the next one
	        App\Error\ErrorMiddleware2::class,
	    ],
	    'error'      => true, 
	    'priority'   => PHP_INT_MAX * -1, // always last
	],

What happen is that only the last error middleware gets invoked.
(Always the one with the lower priority)

In both error middleware `__invoke` i logged into a file 
and only `ErrorMiddleware2` shows up.

Here is the error middleware code (same for both):
 
	namespace App\Error;

	use Zend\Stratigility\ErrorMiddlewareInterface;
	use Psr\Http\Message\ServerRequestInterface;
	use Psr\Http\Message\ResponseInterface;
 
	class ErrorMiddleware implements ErrorMiddlewareInterface
	{ 
	    protected $errorAction;
 
	    public function __construct(ErrorAction $errorAction)
	    {
	        $this->errorAction = $errorAction;
	    }
 
	    public function __invoke(
	        $error,
	        ServerRequestInterface $request,
	        ResponseInterface $response,
	        callable $out = null
	    ) {
	    	// test logging
	        file_put_contents('data/test.txt', __METHOD__. PHP_EOL, FILE_APPEND);

	        // some error handling ...
	        
	        if ($out !== null) {
                // expecting here to invoke the Next() error middleware
	            return $out($request, $response, $error);
	        }
	        return $response;
	    }
	}

I trigger the error middleware from an action like:
`return $next($request, $response, new \Exception('Test Error', 13));`
or
`return $next($request, $response, 'my eString');`

EDIT: using zend expressive skeleton minimal, zend router, zend service manager, no template engine, no whoops / no default error middleware

**Comment by xtreamwayz** [comment]
I don't think that's the right way to configure multiple ErrorMiddleware. This is working for me:

```php
    'middleware_pipeline' => [
        'always' => [
            'middleware' => [
                Expressive\Helper\ServerUrlMiddleware::class,
                // ...
            ],
            'priority'   => 10000,
        ],

        'routing' => [
            'middleware' => [
                Expressive\Container\ApplicationFactory::ROUTING_MIDDLEWARE,
                // ...
                Expressive\Container\ApplicationFactory::DISPATCH_MIDDLEWARE,
            ],
            'priority'   => 1,
        ],

        'error' => [
            'middleware' => [
                App\Core\Security\UnauthorizedErrorMiddleware::class,
                App\Core\Security\ForbiddenErrorMiddleware::class,
                App\Core\Middleware\ExceptionLoggerMiddleware::class,
            ],
            'error'      => true,
            'priority'   => -10000,
        ],
    ],
```

**Comment by cottton** [comment]
Both should do it. But i found out i made a mistake with the priority.
One error middleware had a priority higher than the actual routing.

	// priority timeline:
	errro middleware1
	routing 
	action (error happen)
	errro middleware2

My fault =)

	[
	    'middleware' => [ 
	        App\Error\ErrorMiddleware::class, 
	    ],
	    'error'      => true, 
	    'priority'   => PHP_INT_MAX, // this one was just wrong
	],
	[
	    'middleware' => [ 
	        App\Error\ErrorMiddleware2::class,
	    ],
	    'error'      => true, 
	    'priority'   => PHP_INT_MAX * -1, 
	],

Thanks for the help!
