### ISSUE TITLE
Creating URLs with routers does not respect middleware's path

### ISSUE THREAD

**Issue by fritz-gerneth** [zendframework/zend-expressive#363]
### Scenario

The situation I found myself into is rather simple and followed the [Segregating your application to a subpath](https://zendframework.github.io/zend-expressive/reference/usage-examples/#segregating-your-application-to-a-subpath) example. Based on the skeleton app, I simply moved the middleware down one path: 

```
    'routing' => [
        'path' => '/sub',
        'middleware' => [
            ApplicationFactory::ROUTING_MIDDLEWARE,
            Helper\UrlHelperMiddleware::class,
            ApplicationFactory::DISPATCH_MIDDLEWARE,
        ],
        'priority' => 1,
    ],
```

Everything worked as expected, moving all paths down and prefixed by `/sub`. As the middleware removes the path from the `ServerRequestInterface`, routing worked without any change too. 
Pathes change as expected:
- `/ -> /sub/`
- `/api/ping -> /sub/api/ping`

You can check out my installed & changed skeleton [here](https://github.com/fritz-gerneth/zend-expressive-skeleton/tree/demo/router-segregation) - just `composer install` it. The only change I made is adding a `path` to the middleware. 
### Issue

However, I am now running into troubles when using the router to assemble URLs. **As the router is not aware of the middleware's path, it does not add the path before the assembled URL but creates the original `/` or `/api/ping` URLs.** While these sure are correct in relation to the middleware, there seems to be no real way to make them absolute in a global context.
### Approach

I tried different approaches on this issue so far:
- Configure a `baseUrl` for the router. While this would make the generated URLs right, as the baseUrl is already removed from the request, routes won't match anymore. Plus it is a static configuration which becomes tricky to handle when having multiple pipped middlewares in different `path`s. 
- Approach as suggested in the [Using a base path](https://zendframework.github.io/zend-expressive/cookbook/using-a-base-path/) cookbook. This actually would do the job - unfortunatelly the same problems arrise as for the router-based approach: static configuration (I have to change the same setting in two locations now) and doesn't work with mutliple pipped middlewares in different paths. 

So I tried to create a custom middleware that sets the baseUrl dynamically based on the pipped middlewares so far:
- Sitting before `ROUTING_MIDDLEWARE`
- Determine the middleware onion so far to determine the path to the current middleware by either
  - compare the original request to the current request
  - Inspect the `removed` segments of the `Next` queue. 
- Inject this as the `baseUrl` for the `UrHelper`. 
- Make it accessible as an additional attribute on the request

However, determining the path to the current middleware seems to be impossible. Neither of the two approaches is possible as the information is not public. 
### Summary

In my oppinion my application/middleware should be completly agnostic frorm the path it is being served from. Any user should be able to move it arround to a new URL/path without affecting the middleware itself. So when my module provides an `/ping` API as a standalone middleware, any user should be to pipe it as the location of their choice (e.g. `/api/ping`, /api/v2/ping` ...) without having the change my implementation. 
Yet when creating links within my application, I still need to be able to create valid URLs, independent on where my middleware is lcoated in the onion.

The best approach I could come up so far is the change the piped middleware implementation a little bit to add the (combined) path to the current middleware to the request. This way, any helper / middleware could inject the baseUrl when required. 

I sure could create individual applications with indivudual configuration each, but this would not allow me to have shared resources across all middlewares (e.g. database)

**Comment by xtreamwayz** [comment]
First of all, if you develop your app inside a new branch in a forked repo, you could never contribute back to project if you want to in the future. At least I asume you eventually want to merge that branch into master once your app is ready. The correct way would be use composer to setup your app and create a new repository:

    composer create-project zendframework/zend-expressive-skeleton <project-path>

So what you did by adding a path to routing in de middleware pipeline is telling expressive to use that routing section only for `/sub`. In other words if you call /api, it never executes that middleware pipeline you prefixed with `/sub`. It would only be called if you request `/sub/api`.

To change the basepath in that cookbook means changing the basepath of your entire application. Your application would then be served from `/sub` on your server.

From what you are saying I think you are looking for changing the routes independently. This can be achieved from changing the route config:

```php
// routes.global.php
    'routes' => [
        [
            'name' => 'api.ping',
            'path' => '/sub/api/v2/ping',        // <-------------- Change it here
            'middleware' => App\Action\PingAction::class,
            'allowed_methods' => ['GET'],
        ],
    ],
```

**Comment by fritz-gerneth** [comment]
I was hopping I can create small modularized components, each providing their own `Application` middleware. On the global middleware configuration, I then could simply move their "mounting" point arround to the path I want the middleware to be located. 

Let's assume I have a module `User`, providing its own `Application` instance. Routes configured for this module could be:
- `/user/`
- `/user/[+d]/`
- `/user/messages/`
and so on. Those routes define a clear API for that module. Yet they do not necessarily define on where the module actually lives in relation to the overall application. 

Depending on where I place this middleware in the global `middleware_pipeline`, the absolute URLs for the `User` module change. 

So let's assume we want the user api first to be located in `/api/`:

```
'middleware_pipeline' => [
        'user_api' => [
            'path' => '/api',
            'middleware' => [
                UserMiddleware::class
            ]
        ],
    ],
```
Now all URLs for this module have an `api` prefixed, which is exactly what I wanted (e.g. `/api/user/`). If I want to change the URL later on, it is as simple as updating the `path` to the new URL. All great so far - I have created a module that simply can be plugged into the location where I want it to be. Someone else might want it to be located somewhere else, and he can. 

Now let's assume a second module, an old fashioned `DiscussionBoard` module, providing the routes:
- `/board/`
- `/board/[+d]/`
- `/topic/[+d]/`

Following the same principle as for the `User` module, I ommit the base URL and let the overarching app decide on this:
```
    'middleware_pipeline' => [
        'user_api' => [
            'path' => '/api',
            'middleware' => [
                UserMiddleware::class
            ]
        ],
        'board_api' => [
            'path' => '/db',
            'middleware' => [
                DiscuasionBoardMiddlware::class
            ]
        ],
    ],
```
Later on, someone decides to move the discussion board to the `api` pipe, and wrap it with some common auth handler:
  ```
  'middleware_pipeline' => [
        'user_api' => [
            'path' => '/api',
            'middleware' => [
                AuthenticationCheck::class,
                UserMiddleware::class,
                DiscuasionBoardMiddlware::class
            ]
        ],
    ],
```
In here, I treat middleware applications pretty much like I'd handle applications with NGINX/Apache and a `Location /api/` block or similar. Modules become decoupled parts of the applications I can freely mount whereever I want.

Now, I certainly could make the `User` and `DiscussionBoard` completly separate, with their own `container.php` and `config.php`, configure their own `basePath` and everything would be fine. Yet this prevents me from having shared resources / references to the other module (e.g. datbase connection, routing to the other module etc). 

I certainly could merge them all together as well and adjust the routes as needed, but then I loose the benefits of having pipped and nested middlewares.

I'll dwelfe further into this on how to create independent, re-usable middlewares :)

**Comment by weierophinney** [comment]
We do have ways to achieve this, but evidently need to document them better.

First, the router's ability to generate a URI is based entirely on what routes are configured in the application itself. If you do not add your routes to the application instance, it cannot generate a URI.

Second, the `UrlHelper` from zendframework/zend-expressive-helpers provides the ability to set the *base path*; when configured, it will prepend that to any routes generated.

The approach to take will be based on how you are creating your nested middleware.

### Sharing the router with the parent

If you are sharing the router with the parent application, you will only need to update the `UrlHelper`. You can do this via middleware:

```php
use Zend\Expressive\Helper\UrlHelper;

$urlHelper = $container->get(UrlHelper::class);
$middleware = function ($request, $response, $next) use ($urlHelper) {
    $originalBasePath = $urlHelper->getBasePath();
    $urlHelper->setBasePath('/api');
    
    $response = $next($request, $response);

    $urlHelper->setBasePath($originalBasePath);
    return $response;
}
```

Let's say the above middleware is defined as a class somewhere, say `UserApiUrlHelperMiddleware`. You could then do this:

```php
'middleware_pipeline' => [
    'user_api' => [
        'path' => '/api',
        'middleware' => [
            UserApiUrlHelperMiddleware::class,
            UserMiddleware::class,
        ],
    ],
    /* ... */
],
```

If you call on the `UrlHelper` from within your `UserMiddleware` after doing this, it will be generated correctly.

### Using an alternate UrlHelper instance with your sub-application

If your sub-application has its own routing, you'll likely have multiple `RouterInterface` instances floating around. As such, you would then need to create an alternate `UrlHelper` instance to pass to those. In such a case, I'd create a factory that extends or decorates `Zend\Expressive\Helper\UrlHelperFactory`, and have it inject the base path for the sub application. You would then, of course, register it as a separate service in your application:

```php
'dependencies' => [
    'factories' => [
        'UserApiUrlHelper' => UserApiUrlHelperFactory::class,
    ],
],
```

You would then also have the factories for your services under that subpath inject the alternate `UrlHelper` service:

```php
return new UserMiddleware(
    $container->get('UserApiUrlHelper')
);
```

### Final notes

Stratigility *does* keep track of the subpath in order to ensure that it can be pushed back onto the URI when proceeding to the next middleware in the stack.  However, Stratigility has no direct integration with routers or helpers, which means it cannot push the current base stack into these as it descends into path-based middleware. As such, you need to compose middleware in your stack in order to manage it manually. Hopefully the above examples will assist you in that.

**Comment by fritz-gerneth** [comment]
Creating a custom `UrlHelper` makes perfect sense to me and seems to be the preferable way as this keeps the routes isolated (and their names). Other modules / sub-applications have to request the `UrlHelper` for a specific application manually, which makes things more explicit.

### Example App
I got an [example ](https://github.com/funct/composable-expressive)using this up and running. Setting up a sub-application in a different path/context is pretty easy now.

### Stratigility 
I have seen Stratigility's path management and that it actually is aware of the preceeding path. While I agree it should not be aware of routers and such, it would be great if there were a way for middleware to have access to its current context. 
For now, I have to set the context of the sub-application's middleware twice, once one the middleware definition [itself](https://github.com/funct/composable-expressive/blob/master/config/autoload/middleware-pipeline.global.php#L65), once it a [different key](https://github.com/funct/composable-expressive/blob/master/config/autoload/middleware-pipeline.global.php#L82), accessible from my middleware. Changing the path, requires changing two locations. Not a big hurdle for now, but something to forget and I'd expect my middleware to handle automatically.

### AppFactory
While implementing the example, I wanted the sub-application's setup and configuration to be the same as when configuring expressive directly. After all, it is just another expressive middleware. Yet the `AppFactory` isn't exactly open for reusage and I had to copy most of its code into a [custom factory](https://github.com/funct/composable-expressive/blob/master/modules/Album/src/AlbumMiddlewareFactory.php).

There actually was only once change it the file (after removing the deprecated parts) - I only had to change the signature of `injectRoutesAndPipeline` to accept an array. This pushed the responsibility of fetching the middleware's config to the `__invoke` method. Making this method `protected` instead of `private` would allow other applications to reuse the `AppFactory` instead of copying everything / coming up with custom means of configuration:

```php
class MyAppFactory extends Appfactory
{
	public function __invoke(ContainerInterface $container)
	{
		$router = $container->get(AlbumRouter::class);
        $app = new AlbumMiddleware($router, $container);
        $albumMiddlewareConfig = $container->get('config')['album_middleware'];
        $this->injectRoutesAndPipeline($app, $albumMiddlewareConfig);
        return $app;
	}
}
```
