### ISSUE TITLE
Integrate new view PhptalRenderer

### ISSUE THREAD

**Issue by xorock** [zendframework/zend-expressive#365]
Hello. I have just finished first version of PhptalRenderer:
https://github.com/xorock/zend-expressive-phptalrenderer

Working example: https://github.com/xorock/zend-expressive-phptalrenderer-example
(is based on Twig skeleton, used components are Zend Router, Zend Servicemanager and Whoops).

Todo:
- I would like to use some of the expression modifiers from ZF1 / Ztal project
- Integrate Twitter Bootstrap and Zend form
- Add tests
- After reading some issues of Plates / Twig renderer I'm not sure if I should create public getTemplate() method for direct access to PHPTAL engine. When it can come in handy? With PHPTAL You can not only parse template files but also string sources. PHPTAL is also great when working with XML documents (current implementation of Zend Diactoros does not have XMLResponse) and allows us to set different output modes (setOutputMode: HTML5, XML, XHTML). It is very hard now to change engine settings and putting everything in PhptalRendererFactory is not a good way.

**Comment by weierophinney** [comment]
When/if you complete the renderer, please open an issue or pull request against the zend-expressive-skeleton repository, as that's where the installer logic for selecting renderers exists.

Thanks!
