### ISSUE TITLE
New parameter in AppFactory class

### ISSUE THREAD

**Issue by raphaelcsilva** [zendframework/zend-expressive#377]
The goal is add parameter for handler in factory, it adds more flexibility to customize application and still use factory.

```php
public static function create(
    ContainerInterface $container = null,
    Router\RouterInterface $router = null,
    callable $finalHandler = null
) {
    $container = $container ?: new ServiceManager();
    $router    = $router    ?: new Router\FastRouteRouter();
    $emitter   = new Emitter\EmitterStack();
    $emitter->push(new SapiEmitter());

    return new Application($router, $container, $finalHandler, $emitter);
}
```
 This change won't break the compatibility for users that not defined the new parameter.

**Comment by weierophinney** [comment]
Our plan is actually to remove the need for a final handler completely, and instead use the middleware system to provide those capabilities; as such, we don't want to add something that will have no use!

Thanks for the suggestion, however!

**Comment by raphaelcsilva** [comment]
Thanks @weierophinney for the feedback.
