### ISSUE TITLE
Regarding composer suggestions...

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-expressive#380]
Since [zend-expressive-router suggests installing the routers](https://github.com/zendframework/zend-expressive-router/blob/master/composer.json#L37) and [zend-expressive-template suggests the template renderers](https://github.com/zendframework/zend-expressive-template/blob/master/composer.json#L33) and since [these 2 packages are in the require-section of zend-expressive's composer.json](https://github.com/zendframework/zend-expressive/blob/master/composer.json#L23) wouldn't it make sense to remove the suggestions in zend-expressive's composer.json for 
zend-expressive-aurarouter,
zend-expressive-fastroute,
zend-expressive-zendrouter,
zend-expressive-platesrenderer,
zend-expressive-twigrenderer,
and zend-expressive-zendviewrenderer?

**Comment by harikt** [comment]
I believe you are correct. Probably you should consider sending a PR. If busy I can send one.

**Comment by weierophinney** [comment]
Closed with #381.
