### ISSUE TITLE
marshalLazyMiddlewareService() incompatible with zend-stratigility 1.3 and http-interop style middleware

### ISSUE THREAD

**Issue by moderndeveloperllc** [zendframework/zend-expressive#389]
zend-stratigility 1.3 just dropped and includes [code to dispatch middleware](https://github.com/zendframework/zend-stratigility/blob/master/src/Dispatch.php#L79) that conforms to the http-interop (soon to be [PSR-15](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware.md) I guess) `ServerMiddlewareInterface` standard. The problem is that `Zend\Expressive\MarshalMiddlewareTrait::marshalLazyMiddlewareService()` wraps middleware in a `Closure`, which therefore bypasses the stratigility `Dispatch` code.

Yes, that code has been deprecated and will be removed in zend-stratigility 2.0, but this should still be resolved as many will stick with 1.3 and gradually migrate to the http-interop middleware style over time. zend-stratigility 2.0 will [require http-interop style middleware](https://github.com/zendframework/zend-stratigility/blob/develop/src/Route.php#L48).

**Comment by weierophinney** [comment]
This planned, and I will be staying work on it shortly:

- https://gist.github.com/weierophinney/a983f733c2ff3c9b3a687625e012e6e1

**Comment by moderndeveloperllc** [comment]
@weierophinney Feel free to close, or leave up if you want others to see.

**Comment by weierophinney** [comment]
#396 will fix this; closing this for now, as the logic is complete, and will be merged to develop soon in preparation for a 1.1 release.
