### ISSUE TITLE
Routing: A route middleware cannot access the actual Route that created it.

### ISSUE THREAD

**Issue by mwillbanks** [zendframework/zend-expressive#39]
Another small item but should be handled.  If the middleware has a route, it should be supplied the route.  At this point you would lose all route options and they would be inaccessible.  This would be particularly helpful when invoking.

**Comment by mwillbanks** [comment]
This is actually solved enough by stealing the matched params; however, might want to consider passing the entire route in :)

**Comment by weierophinney** [comment]
> might want to consider passing the entire route in

The question is: what do we call the attribute? We need a name that's unique and not likely to be overwritten by route match parameters.

Send me a PR with your ideas on this one. :)
