### ISSUE TITLE
Use PSR7 interfaces in match

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#4]
Hi,

I've just had a quick look at the code, and it seems the `match` could accept a ServerRequestInterface instead (https://github.com/zendframework/zend-expressive/blob/master/src/Router/RouterInterface.php#L19). That would make things easier and a great way to take advantage of those interfaces from start to end. It seems that next version of Aura.Router that you rely on supports this directly: https://github.com/auraphp/Aura.Router/blob/3.x/src/Matcher.php#L110

For adapter that do not support it (like FastRoute), a transformation should be done before passing the info.

**Comment by ezimuel** [comment]
@bakura10 thanks for your comment! The goal of the route adapter is to offer an easy way to integrate external routing system, even if not PSR-7 compliant.  I think the interface `match($path, $params)` is more general then `match(ServerRequestInterface $request)` and offers an easy way to integrate also PSR-7 using the following code:
```php
$path =  $request->getUri()->getPath();
$params = $request->getServerParams();
```

**Comment by bakura10** [comment]
Hi,

Seen otherwise, the transform could be made in the match for library that do not support it (untested code, just the idea):

Example in Aura that supports passing PSR7 interface:

```php
/**
     * @param  string $patch
     * @param  array $params
     * @return boolean
     */
    public function match(ServerRequestInterface $request)
    {
        $this->route = $this->router->match($request);
        return (false !== $this->route);
    }
```

For those that do not support it: 

```php
/**
     * @param  string $patch
     * @param  array $params
     * @return boolean
     */
    public function match(ServerRequestInterface $request)
    {
        $request = ServerRequestFactory::fromGlobals();

        $dispatcher = new Dispatcher($this->router->getData());
        $result     = $dispatcher->dispatch($request->params(), $request->path());
        if ($result[0] != Dispatcher::FOUND) {
            return false;
        }
        $this->routeInfo = $result;
        return true;
    }
```

In short terms most library should comply with PSR7 :).

**Comment by ezimuel** [comment]
@bakura10 we discussed with @weierophinney and we decided to use the the PSR-7 for the routing interface. We did an entire refactor of the implementation. You can see it [here](https://github.com/zendframework/zend-expressive/blob/master/src/Router/RouterInterface.php) and thanks for your feedback!
