### ISSUE TITLE
Add getter to retrieve configured routes

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-expressive#421]
Per [a comment detailing how to handle modules in the Expressive skeleton](https://github.com/zendframework/zend-expressive-skeleton/pull/54#issuecomment-266516866), we need to expose a getter to allow users/tooling to retrieve the routes. Since routes are already stored as a property of the `Application` instance, we can add the following:

```php
/**
 * Retrieve the set of currently registered routes.
 *
 * @return Router\Route[]
 */
public function getRoutes()
{
    return $this->routes;
}
```

**Comment by Ocramius** [comment]
-1 on this: make it a service instead?

**Comment by weierophinney** [comment]
Routes are created and added when calling `get()`, `post()`, etc.; router implementations are not guaranteed to store the original instances. As such, the `Application` instance is the canonical location for storing them. 

Knowing that, what would you recommend, @Ocramius ?

**Comment by Ocramius** [comment]
Ouch, don't see a way out of an accessor then 😥

**Comment by krzysiekpiasecki** [comment]
"Visitor" ?

```
public function routes(RouteCollectorInterface collector): RouteCollectorInterface;
```

**Comment by Ocramius** [comment]
@krzysiekpiasecki overkill for this scenario - I was just hoping for simply *not* expanding the API on the `Application` object, at all.

**Comment by weierophinney** [comment]
#426 resolves this and has been merged to the develop branch.
