### ISSUE TITLE
Question: v1.1.0 - Stratigility 1.3.x or 2.0.x?

### ISSUE THREAD

**Issue by moderndeveloperllc** [zendframework/zend-expressive#427]
@weierophinney Is the current plan to move the 1.1 branch to stratigility 2, or wait till a future version (1.2 or 2.0)? I don't want to waste your time or mine by creating pull requests on `develop` if the plan is to wait.

**Comment by weierophinney** [comment]
The develop branch has been messaged as an upcoming version 1.1. However, we want to adopt Stratigility 2.0, as that is implementing the latest http-interop/http-middleware interfaces — but as that introduces BC breaks that impact Expressive, it means that we will need to bump to a new major version. As such, develop will become 2.0.0.

I'm currently working on the Stratigility 2.0 integration against the develop branch, and have been for the last day and a half; it affects a ton of functionality, so it's slow going. I anticipate being done and submitting the pull request tomorrow.
