### ISSUE TITLE
Help - Uploading file

### ISSUE THREAD

**Issue by guilherme90** [zendframework/zend-expressive#430]
Hi guy, all right? I'm uploading the file, but the $request->getUploadedFiles() method is returning me an empty array. I honestly do not know why. Can you help me?

I have noticed that I submit the form for an action of it, so I can get it back using getUploadedFiles, but I send it to a different action, this method comes empty.

After all, how do I capture using a different action?

[See this gist](https://gist.github.com/guilherme90/ff2e2600451836210a3bdc96f8a8eda7)

![img-return](https://cloud.githubusercontent.com/assets/2879939/22406368/465a39e6-e639-11e6-888b-a36a09af96d8.png)

Thanks :)

**Comment by ozzpy** [comment]
is on your form set the property multiform part/data?

**Comment by xtreamwayz** [comment]
I just had a quick look and your code seems fine. However it seems that you expect that `$request->getUploadedFiles();` returns an array. It does, but each key in that array contains a `Psr\Http\Message\UploadedFileInterface` [object](https://github.com/zendframework/zend-diactoros/blob/master/src/UploadedFile.php). So dumping that object doesn't do much since that object doesn't implement JsonSerializable.

**Comment by weierophinney** [comment]
Another point to note: by default, `getUploadedFiles()` uses what is in the `$_FILES` array to seed the `UploadedFile` instances; however, this fails when you have a non-POST request and/or a non-`multipart/form-data` content type. In those situations, you will need to register middleware to parse the incoming data into `UploadedFile` instances. Unfortunately, I'm not aware of any implementations to date that provide this (we provide this within the zf-content-negotiation module of Apigility, but that isn't setup yet to work with PSR-7). If this is the situation you find yourself in, you may want to look at that module to see how you might write such middleware.

**Comment by guilherme90** [comment]
Hey, guys! Problem solved...
Yeah, i debug a print_r in `$request->getUploadedFiles();` and return **\Zend\Diactoros\UploadedFile**

Thanks and sorry for all.
