### ISSUE TITLE
ZendRouter generates Missing parameter

### ISSUE THREAD

**Issue by Kuzry** [zendframework/zend-expressive#471]
I have a route definition:

```
new Route(
    '/:lang/sign-up/activation/:id[/:code]/'
    \App\Action\SignUp\Activation::class,
    ['GET'],
    'sign_up.activation'
);

$route->setOptions([
    'constraints' => [
        'lang' => 'en|pl',
        'id' => '[a-z0-9]{20}',
        'code' => '[a-z0-9]{6}'
    ],
    'defaults' => [
        'lang' => 'en'
    ],
]);
```

Then I generate route:

```
$this->urlHelper->generate('sign_up.activation', [
    'lang' => $request->getAttribute('lang'),
    'id' => '12312312312312312312',
]));
```

This generate exception: Zend\Router\Exception\InvalidArgumentException Missing parameter "code"

Is this a default behavior or am i doing something wrong?

**Comment by Vandervir** [comment]
It looks like that You missed default value for code in setOptions method.

**Comment by Kuzry** [comment]
Is default value required for optional parameter?

When I add default value, generated url will always has value with optional parameter. But I want my url sometimes with code and sometimes without code.

**Comment by Vandervir** [comment]
That should make regex optional

`        'code' => '[a-z0-9]{6}|'`

**Comment by Kuzry** [comment]
Thanks @Vandervir for your answer, but this still does't work. Same issue.

**Comment by harikt** [comment]
@Kuzry I haven't played with zend-router. So I may be wrong.

Just try adding a `?` to either the constraint or on the route path `[/:code?]`.

**Comment by Kuzry** [comment]
Ok, i found that:
[https://github.com/zendframework/zend-expressive/issues/186](url)
[https://github.com/zendframework/zend-expressive-zendrouter/issues/4](url)
