### ISSUE TITLE
LazyLoadingMiddleware suggestion

### ISSUE THREAD

**Issue by n3vrax** [zendframework/zend-expressive#474]
Hi guys,

I was wondering if it wouldn't be good to have a getter in `LazyLoadingMiddleware` class to the the middleware service's name, as I'm often put in the situation of needing that, and I guess I'm not the only one that would need that, and I don't like the idea of using reflection just for that.

Situations when you need the middleware names are for example when writing configuration driven libraries that work on a per middleware basis(like globally configured authorization, content validation etc.)

Version ^1.0 had that in the RouteResult -> getMatchedMiddleware() even if lazy loaded
Or better, a new method for the RouteResult that would always return the middleware stack names.

I'm open to suggestions on achieving this, maybe I am missing something and there is already a method for it

Thanks!
Tiberiu

**Comment by Ocramius** [comment]
Could you please make a usage example first? What's the use-case scenario?

**Comment by n3vrax** [comment]
I needed this when developing a content validation library for example.
The setup is:
* i have routed middleware(for api endpoints)
* i need to configure a content validation middleware, after routing and before dispatching
* the configuration is per routed middleware, so in the configuration file I use the middleware class name as key, to associate an input filter to it(this is much like what apigility is doing)

```php
'dot_content_validation' => [
        'controllers' => [
            FooResource::class => [
                // the route param name used to identify a resource
                'identifier_name' => 'id',

                // the below flag is not used yet, reserved for future use
                'validate_uploaded_files' => false,

                // return api error when request data has unknown fields
                'allow_only_validated_fields' => true,

                // configure input filters to apply
                'validation' => [
                    'input_filter' => 'FooInputFilter',
                    // 'GET' => 'GetFooQueryParamsInputFilter'
                    // 'POST' => 'CreateFooInputFilter',
                    //...
                ],
            ],
        ],
    ],
```

Now, in the content validation middleware I need to get the input filter from the manager, as configured
For now, I solved it by using reflection like this
```php
protected function getMiddlewareName($middleware): string
    {
        if (is_string($middleware)) {
            return $middleware;
        }

        if ($middleware instanceof LazyLoadingMiddleware) {
            $class = new \ReflectionObject($middleware);
            $middlewareProperty = $class->getProperty('middlewareName');
            $middlewareProperty->setAccessible(true);
            return $middlewareProperty->getValue($middleware);
        }

        if (is_object($middleware)) {
            return get_class($middleware);
        }

        return '';
    }
```

I'm fairly happy for now with this, I don't know what the performance hit would be in this case, but I try to avoid reflection when possible.

**Comment by Ocramius** [comment]
> I use the middleware class name as key

Ah yes, I use the same for something like authentication/authorization firewalls. Good catch, although the reflection approach is indeed terrible :|

So routing does no longer provide the middleware name, but just an instance? :S

**Comment by wesperinteractive** [comment]
My usage example:

Most of my actions (routed middlewares) are using templates. A don't really want to create custom factories for each and inject the template renderer etc... So i created a TemplateRendererMiddleware, i piped it right after the DispatchMiddleware.

```
public function process(ServerRequestInterface $request, DelegateInterface $delegate)
{
    if (! ($result = $request->getAttribute(RouteResult::class, false))) {
        return $delegate->process($request);
    }

    $middlewareClass = get_class($result->getMatchedMiddleware());
    $templateName = $this->convertMiddlewareClassToTemplateName($middlewareClass);
    $templateVariables = $request->getAttribute('templateVariables');

    return new HtmlResponse($this->template->render($templateName, $templateVariables));
}
```

I recieve the template variables form the action (withAttribute / getAttribute). Unfortunately the value of the $middlewareClass will be "Zend\Expressive\Middleware\LazyLoadingMiddleware" and not not e.g. "Cms\Action\IndexAction". From that i could create the name of the template (cms::index).

**Comment by moderndeveloperllc** [comment]
This isn't a "real" solution to your problem, but I use `getMatchedRouteName()` from the `RouteResult` class. I use that to validate input against a JSON Schema via [JSON Guard](https://github.com/thephpleague/json-guard). I use the FastRoute router, so each of my routed middleware look something like:
```
$engine->route('/ping', Engine\RoutableAction\PingAction::class, ['GET'], 'ping');
```
I then use it in abstract class for all by `RoutableAction` classes via:
```
$this->routeName = ($request->getAttribute(RouteResult::class))->getMatchedRouteName();
```
In my case, there is a 1-to-1 relation between middleware and route name. Not a programmatic solution, but it might help in the interim.

**Comment by wesperinteractive** [comment]
It can be a solution if i name all of my routes the "same" way as my action classes. 

`$app->get('/cms', Action\IndexAction::class, 'cms_index');`

And from "cms_index" (getMatchedRouteName) i can convert the template name "cms::index" :)

**Comment by moderndeveloperllc** [comment]
@wesperinteractive Yeh, that would work. It's documentation-as-code which can break pretty easy if you or the programmer after you forgets about how that works. But at least it works until something can be made for a programmatic fix.

**Comment by weierophinney** [comment]
There are multiple solutions to this problem presented here, none of which require code changes within the component; closing.
