### ISSUE TITLE
Template caching

### ISSUE THREAD

**Issue by guilherme90** [zendframework/zend-expressive#481]
Hi...

Is it possible to implement the template cache? This project is for Zf2 / Zf3, but does it have the same for Expressive?

https://github.com/Ocramius/OcraCachedViewResolver

**Comment by froschdesign** [comment]
@guilherme90 
Caching with a middleware architecture is not difficult:
https://framework.zend.com/blog/2017-04-19-caching-middleware.html

**Comment by guilherme90** [comment]
Thanks :)

**Comment by froschdesign** [comment]
If you have more questions, please use the _new_ [Zend Framework Forum](https://discourse.zendframework.com/c/questions/expressive). Thanks!
