### ISSUE TITLE
How are you organizing your factories as your project gets larger?

### ISSUE THREAD

**Issue by exts** [zendframework/zend-expressive#483]
Seems like there's a growing amount of factory classes as my project gets larger with more actions and middleware there's a paired factory to inject the dependencies I need for each and it seems just a bit unorganized by just throwing the factory class in the same folder.

Maybe it's just a weird feeling since this is the first time I've done single action classes instead of controllers which paired all these actions in one file and I'd only have to deal w/ one file to inject the dependencies rather than say 8 for a basic CRUD (pairing each one w/ factories for injecting for examples.

Is it just something I need to get used to, or is there a way to organize all these factory files?

**Comment by froschdesign** [comment]
With [zend-servicemanager](https://docs.zendframework.com/zend-servicemanager/) you have some options to reduce the number of factory classes:

- [Abstract factories](https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/#abstract-factories)
- [Config Abstract Factory](https://docs.zendframework.com/zend-servicemanager/config-abstract-factory/)
- [Reflection Factory](https://docs.zendframework.com/zend-servicemanager/reflection-abstract-factory/)

Look also at this tutorial from Matthew Setter: "[How To Do RAD Prototyping and Development With The ReflectionBasedAbstractFactory](http://www.masterzendframework.com/rad-prototyping-and-development-with-reflectionbasedabstractfactory/)"

**Comment by exts** [comment]
Thanks for the resources :). I also just learned that middleware sent through the pipe doesn't require factories which is nice.

**Comment by froschdesign** [comment]
Btw. please add your further questions to the _new_ [Zend Framework Forum](https://discourse.zendframework.com/c/questions/expressive), because this is a bug tracker and not a support forum. Thanks!

**Comment by exts** [comment]
@froschdesign that expressive link doesn't exist, don't think there are individual forums yet or it's not public to guest users?

**Comment by froschdesign** [comment]
@exts 
Mmmh, Login should help.

**Comment by froschdesign** [comment]
ping @weierophinney

**Comment by exts** [comment]
@froschdesign works now

**Comment by kynx** [comment]
Not for me :(

> Error
> while trying to load
> Something went wrong.

**Comment by exts** [comment]
@kynx make sure you're logged in

**Comment by froschdesign** [comment]
@kynx 
Problem fixed! See: [zendframework/zf3-web#68](https://github.com/zendframework/zf3-web/pull/68#issuecomment-300489174)
