### ISSUE TITLE
[Question] Use any PSR-7 implementation?

### ISSUE THREAD

**Issue by shadowhand** [zendframework/zend-expressive#491]
My application already uses Guzzle, which has a [complete PSR-7 implementation](https://github.com/guzzle/psr7) that comes with it. What would be required to make Expressive use this implementation of PSR-7 instead of Diactoros?

**Comment by shadowhand** [comment]
I know of at least two things that prevent the usage of [`psr/http-message-implementation`](https://packagist.org/providers/psr/http-message-implementation) instead of `zendframework/zend-diactoros`:

1. The usage of [emitters](https://github.com/zendframework/zend-expressive/blob/3abb745e024082d7558acbe08a18891a20b4cc8e/doc/book/features/emitters.md) is non-standard. Perhaps [http-interop/response-sender](https://packagist.org/packages/http-interop/response-sender) can help with this.
2. Diactoros includes some "prefab" responses like `EmptyResponse` and `HtmlResponse`. There is actually nothing unique about these, as they are actually factories that manipulate the response headers and body. An extension (or wrapper) of [http-interop/http-factory](https://packagist.org/packages/http-interop/http-factory) would work equally well.

**Comment by kynx** [comment]
FWIW I _return_ guzzle responses from my middleware with no problems. Expressive only cares that the response implements PSR7. This makes for a very easy and lightweight way to proxy remote services. 

I haven't had the need, but I can't see any reason you couldn't build and return things like their PumpStream too. But it sounds like you want to completely replace Diactoros?

**Comment by shadowhand** [comment]
@kynx my goal is that Expressive depend on `psr/http-message-implementation` instead a concrete implementation. That's the goal of PSRs, right? 😁

**Comment by moderndeveloperllc** [comment]
@shadowhand You may want to take this discussion to the [discourse site for Expressive](https://discourse.zendframework.com/c/questions/expressive) since this looks to be something that will provoke lots of discussion. @weierophinney seems to be more active over there for questions like this.

**Comment by Xerkus** [comment]
zend-expressive did not depend on diactoros for its PSR-7 implementation but for its response emitters.

Code for firing off request handler, handling exceptions and emitting response was extracted into `zendframework/zend-httphandlerrunner` component.
Zend-expressive v3 switched to that component and does not depend on zend-diactoros anymore.

For version 3 you would need to override factories for `Psr\Http\Message\ResponseInterface`, `Psr\Http\Message\ServerRequestInterface` and `Psr\Http\Message\StreamInterface`
Note that those services are in fact callable factories and not actual instances implementing interfaces
https://github.com/zendframework/zend-expressive/blob/4e551cd318584ddba4fdc529264e0037cac11a6a/src/ConfigProvider.php#L56-L59

Any further questions should be directed to our [chat](https://zendframework.slack.com/) ([signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).
