### ISSUE TITLE
Body Parsing documentation is out of date

### ISSUE THREAD

**Issue by shadowhand** [zendframework/zend-expressive#492]
https://docs.zendframework.com/zend-expressive/features/helpers/body-parse/ refers to pre-v2 configuration pipelines. The actual solution is much simpler:

```php
use Zend\Expressive\Helper\BodyParams\BodyParamsMiddleware;

// ...

$app->pipe(BodyParamsMiddleware::class);
```

**Comment by harikt** [comment]
@shadowhand so what is the solution ? How about you send a PR with the changes ?

**Comment by xtreamwayz** [comment]
It's already mentioned???

Right under https://docs.zendframework.com/zend-expressive/features/helpers/body-parse/#registering-the-middleware

**Comment by harikt** [comment]
@xtreamwayz I am also wondering about it. But not sure whether @shadowhand is telling something else.

**Comment by shadowhand** [comment]
@xtreamwayz doh! you're right. I completely missed that line because it is so tiny compared to all the (outdated) information about using configured pipeline.

I'll leave this open since the docs could do a better job of separating between current and deprecated usage.

**Comment by xtreamwayz** [comment]
I agree on the mess it causes and I've brought this to the attention of mwop a few weeks ago. I did some research and I haven't found an existing system that could handle this in our use case. I've got some ideas on how to do this properly with versioning but it involves writing something from scratch and I haven't had the time yet to work on it.

Basically the idea is to generate and upload the docs grouped by minor versions:

```
https://docs.zendframework.com/<component>/<version|latest|develop>/getting-started/features/
```

```
https://docs.zendframework.com/zend-expressive/1.1/getting-started/features/
https://docs.zendframework.com/zend-expressive/2.0/getting-started/features/
https://docs.zendframework.com/zend-expressive/latest/getting-started/features/
https://docs.zendframework.com/zend-expressive/dev/getting-started/features/
```

GitHub would trigger a document server if a new version is tagged so it can regenerate the docs for that specific version. Or in case something is pushed to the develop branch it would always regenerate the develop docs.

**Comment by xtreamwayz** [comment]
Closing this as the issue mentioned wasn't really an issue and suggested versioning of the docs is now available.
