### ISSUE TITLE
Speed?

### ISSUE THREAD

**Issue by guilhermeaiolfi** [zendframework/zend-expressive#500]
Hi,

after implementing/studying all the bits I needed to migrate one big site created using Agavi Framework I went and benchmarked it against the Agavi implementation. To my surprise, expressive was slower than agavi. Agavi used to be one of the slowest frameworks back in 2011. I don't know how it would perform against laravel and symfony today but Agavi is no near close to a lightweight framework.

I have added 3 middlewares and used the auryn Container. But no middleware is doing heavy stuff, no more than 3 ou 4 ifs to control the flow. There is only 4 routes defined. Simple templates (actually there is no loop in any template).

For a simple view using plates and one query to the DB (using zend DB) it was ~30% slower than the front page of the current site I want to implement in it (yes, I tested in the same machine, quering the same database). 

The Agavi based front page is doing a LOT more than the zend-expressive counterpart. 

The config cached version of zend-expressive was even slower than the no cached version of Agavi.

I will start investigating deeper tomorrow but I want to start the discussion around SPEED. 

There is anyone else benchmarking zend-express? Please share your results.

**Comment by moderndeveloperllc** [comment]
@guilhermeaiolfi You will probably want to take this to the discourse server here: https://discourse.zendframework.com/c/questions/expressive. That is the appropriate place for discussions. FWIW, you will probably need to provide code for what you are doing in Expressive so folks can figure our where you are having issues.

**Comment by Ocramius** [comment]
Also, an xdebug profile would help a lot.

**Comment by sandrokeil** [comment]
@guilhermeaiolfi You can also use the [blackfire profiler](https://blackfire.io/). Feel free to use one of the [prooph Docker images](https://hub.docker.com/r/prooph/php/).

**Comment by xtreamwayz** [comment]
Closing this. For questions and discussions like this our [forum](https://discourse.zendframework.com/c/questions/expressive) are the perfect place. There are already some topics on this:

- https://discourse.zendframework.com/t/expressive-swoole-vs-node-js-express-js/439
- https://discourse.zendframework.com/t/expressive-performance-benchmarks-2-vs-3/505
