### ISSUE TITLE
Replace Application's __call magic method

### ISSUE THREAD

**Issue by jansvoboda11** [zendframework/zend-expressive#504]
The argument reflowing in `__call` magic method on `Zend\Expressive\Application` is very confusing an unnecessarily complex.
I think that adding real `get`, `post`, `put`, `patch` and `delete` methods would be simpler.
The public API of the class wouldn't change, so this is not a breaking change.
Currently, the `Application` class provides signature of the routing methods via PHPDoc, but IDE's like PhpStorm get confused when extending and overriding those methods.

**Comment by samsonasik** [comment]
should be close-able in favor of #505
