### ISSUE TITLE
ImplicitOptionsMiddleware: Set Access-Control-Allow-Methods?

### ISSUE THREAD

**Issue by moderndeveloperllc** [zendframework/zend-expressive#506]
One of the nice things about ImplicitOptionsMiddleware is that it is a great way to handle pre-flight checks for AJAX calls (OPTIONS calls). It correctly returns the `Allow` header, but I was  wondering if it would be appropriate to also add the `Access-Control-Allow-Methods` header as that is needed for some cross-domain AJAX calls. Browsers seem to do POST and GET calls without the extra header, but others like DELETE need have the `Access-Control-Allow-Methods` header set.

**Comment by webimpress** [comment]
@moderndeveloperllc If you need to add headers `Access-Control-Allow-*` you need to use a custom middleware. As you mentioned, they are needed in case of cross-domain AJAX requests, so it's not going to be used always, in all applications. Not sure if it will be interest to include it into the expressive - it must be configurable for each case. If you'd like to submit your PR I'd be happy to review and test it 😄

**Comment by moderndeveloperllc** [comment]
@webimpress I've submitted it as #507. It's not a big change. Just add the header only if it's asked for. By this point in `process()` we have passed all the short-circuits, so this shouldn't add much processing time at all.
