### ISSUE TITLE
Suggestion for posting issue

### ISSUE THREAD

**Issue by jkhaled** [zendframework/zend-expressive#509]
I find the flow framework team template for describing issue interesting  , hope can be applied at zend 

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Affected Versions

Zend framework:

others:

You can get this information by running `composer show`.

**Comment by weierophinney** [comment]
We are working on unified issue and PR templates already; please see zendframework/maintainers#18

Once approved, we'll roll them out to all repositories.

**Comment by jkhaled** [comment]
Good :)
