### ISSUE TITLE
Will there be a `content-validation` component in the future?

### ISSUE THREAD

**Issue by Moln** [zendframework/zend-expressive#531]
I think  `zfcampus/zf-content-validation` is a good components. But it is not a PSR7 component.
I tried create the same component  [zfegg/content-validation](https://github.com/zfegg/content-validation ).  But my team is not strong enough.

Is there a roadmap to create a PSR7 `content-validation` component.

**Comment by weierophinney** [comment]
Yes, there will, but it requires changes to existing components and/or needs new components to accomplish. (Validators and input filters need to be stateless to ensure error messages are not incorrectly propagated.) We've already started work, and the roadmap is on our forums: https://discourse.zendframework.com/t/rfc-new-validation-component/208
