### ISSUE TITLE
Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by lpj145** [zendframework/zend-expressive#532]
When i tried use closure on config, i get this error, now i can understand problem is a closure, if i put on factory can't receive this error, somebody pass to this problem ?

![image](https://user-images.githubusercontent.com/11980109/33682315-d8ffcd54-daa5-11e7-9f31-f4c33f498e61.png)

**Comment by weierophinney** [comment]
You mention "use closure on config", but don't provide more specific details; is this to provide a one-off factory for a service?

If so, this is a known issue, and something that requires a change in your code.

By default, in production mode, we cache configuration. Caching configuration requires serializing the merged configuration to a single, includable file. Unfortunately, PHP is incapable of serializing closures, so you cannot include closures within your configuration files.

The solution is to only specify factory class names or named functions in those cases.

**Comment by lpj145** [comment]
ok, if not can possible add closure on production environment, please remove it from tutorial.

**Comment by froschdesign** [comment]
@lpj145 
> please remove it from tutorial.

Which tutorial do you mean? Thanks!

**Comment by lpj145** [comment]
Thanks, i think tutorial is on expressive home page, but i see it on other tutorial, thanks for fast reply.

If i ask, when yours release 3.x version ?

**Comment by froschdesign** [comment]
> Thanks, i think tutorial is on expressive home page

I searched the documentation files, but I found nothing. It would be great, if you have a link to point me in the right direction.
