### ISSUE TITLE
IMPLICIT_HEAD_MIDDLEWARE_STREAM_FACTORY doesn't return the factory as a service

### ISSUE THREAD

**Issue by tommyseus** [zendframework/zend-expressive#552]
### Branch
release-3.0.0

### Error
The Router\IMPLICIT_HEAD_MIDDLEWARE_STREAM_FACTORY doesn't return the factory as a service. It returns a \Zend\Diactoros\Stream instance.

Argument 2 passed to Zend\Expressive\Router\Middleware\ImplicitHeadMiddleware::__construct() must be callable, object given, called in /var/www/application/vendor/zendframework/zend-expressive-router/src/Middleware/ImplicitHeadMiddlewareFactory.php on line 55

### Fix
Maybe as Invokable or FactoryFactory.

```php
'invokables' => [
	Router\IMPLICIT_HEAD_MIDDLEWARE_STREAM_FACTORY => Container\StreamFactory::class,
]
```

or

```php
'factories' => [
	Router\IMPLICIT_HEAD_MIDDLEWARE_STREAM_FACTORY => Container\StreamFactoryFactory::class,
]
```

**Comment by weierophinney** [comment]
Fixed with #553.
