### ISSUE TITLE
ResponseInterface points to a callable

### ISSUE THREAD

**Issue by drigani** [zendframework/zend-expressive#569]
In the release `3.0.0alpha9` more precisely `src/ConfigProvider.php` we found that definition of `ResponseInterface::class` in the line 54 is:
```php
ResponseInterface::class => Container\ResponseFactoryFactory::class,
```
The problem with that is that the component [https://github.com/zendframework/zend-expressive-authentication](https://github.com/zendframework/zend-expressive-authentication) when retrieving a ResponseInterface from the container, the new definition returns a callable, but the return type hinting of `\Zend\Expressive\Authentication\ResponsePrototypeTrait::getResponsePrototype` expects a `ResponseInterface`

**Comment by xtreamwayz** [comment]
Fixed in zendframework/zend-expressive-authentication#18.
Merged into [zend-expressive-authentication 1.0.0alpha3](https://github.com/zendframework/zend-expressive-authentication/releases/tag/1.0.0alpha3).
