### ISSUE TITLE
V3 MiddlewareContainer is not PSR container compatible

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-expressive#573]
`MiddlewareContainer::get()` throws `Exception\MissingDependencyException` and `Exception\InvalidMiddlewareException`. These exceptions imho should extend/implement [PSR exceptions](https://github.com/php-fig/container/blob/master/src/ContainerInterface.php#L23).

**Comment by weierophinney** [comment]
Fixed with #574.
