### ISSUE TITLE
What is container?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#6]
Hi,

What is the goal of those lines: https://github.com/zendframework/zend-expressive/blob/master/src/App.php#L93

It seems that the App has no container. Judging from the exception it seems you are using the Interop interfaces. Maybe the container could set as a dependency in constructor?

**Comment by samsonasik** [comment]
@bakura10 I think that indeed a container interop interface. As for zf, we can consume this in new skeleton and inject with ServiceManager? /cc @ezimuel

**Comment by weierophinney** [comment]
@samsonasik This is separate from the zf2 mvc layer.

**Comment by bakura10** [comment]
This is what I understand @weierophinney , but I REALLY love the lightweight architecture in that kind of library, and I'd love to actually use that. However as said on Twitter, I'm really a bit lost about where all this is going, mainly by the lack of visibility of where the Zend team is leading, and how everyting should interact together.

I can definitely see the advantages of that kind of project (Zend-Expressive...) for API driven proejcts, where the Zend\Mvc is really more complex that waht I need. But for this to work it would be awesome to have some more complex example, and how it could be integrated inside the existing ZF modules. For instance: how could I use Zend\Expression with a module like SlmQueue that rely on the ZF config?

I'd love to have the general goal of all this. As I see how it evolves (and tbh I LOVE how it is evolving - aka smaller packages with a very focused goal), the mid-term goal is to kinda deprecate usage of Zend\Mvc (and the router), and use a third-party router (I don't see Dasprid those times so I don't really know where his Dash router is going), and create a new, minimal, decoupled Zend\ModuleManager that could work with it.

If we take advantage of the Container Interop, PSR7... all of this could work smoothly, and I'd be happy to help to write some code.

**Comment by samsonasik** [comment]
we don't know instead of guess-ing as the repository already public, what the plan for its usage? it's regarding with zf3 implementation?

**Comment by weierophinney** [comment]
In the ZF3 roadmap post, we indicated we'd provide a middleware-based
application solution in *parallel* with the current MVC. This is the start
of that. *It doesn't replace the MVC.* (And it will potentially require its
own skeleton, which was the first of my original reply to you.)

I'll provide a more full explanation next week so you don't have to keep
guessing. In the mean time, consider it a work in progress, and maybe sit
back to see how we flesh it out before diving too deep into the code. (I
have a considerable refactor that's based around use cases almost ready to
post, and it will likely shed more light on our intentions.)

**Comment by samsonasik** [comment]
thank you ;)

**Comment by ezimuel** [comment]
@bakura10 we are working to offer a simple solution to start writing web application using middleware, not only APIs. At the same time we want to continue to support the MVC for different use cases. ZF3 will support both! 
We did a huge refactor of zend-expressive, incorporating most of the discussion with @weierophinney and collection feedbacks. I think you will enjoy the new implementation.
