### ISSUE TITLE
handler:create produces template in wrong location

### ISSUE THREAD

**Issue by JalfResi** [zendframework/zend-expressive#604]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

From a fresh skeleton project install, create a new module with a new handler. I issued the following commands:

```bash
composer create-project zendframework/zend-expressive-skeleton ze3-app
# (modular, zend-servicemanager, FastRoute, Twig and Whoops)

./vendor/bin/expressive module:create Staff
./vendor/bin/expressive handler:create Staff\\Action\\ListAll
```

### Code to reproduce the issue

```bash
composer create-project zendframework/zend-expressive-skeleton ze3-app
# (modular, zend-servicemanager, FastRoute, Twig and Whoops)

./vendor/bin/expressive module:create Staff
./vendor/bin/expressive handler:create Staff\\Action\\ListAll
```

### Expected results

The list-all.html.twig file should be created in the new Staff module templates directory.

### Actual results

A new directory was created in the project route:

/Users/ben.davies/Documents/projects/ze3-app/src/Staff/src/templates/list-all.html.twig

Looking at the output of the handler:create command I can see the following:

```bash
- Created template staff::list-all in file /Users/ben.davies/Documents/projects/ze3-app//Users/ben.davies/Documents/projects/ze3-app/src/Staff/src/../templates/list-all.html.twig
```

On MacOS.

PHP 7.1.14 (cli) (built: Feb  6 2018 16:24:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by xtreamwayz** [comment]
This should be reported at [zendframework/zend-expressive-tooling](https://github.com/zendframework/zend-expressive-tooling/issues).

**Comment by JalfResi** [comment]
Thanks! Closing
