### ISSUE TITLE
PHP-DI - Container -Suggestion

### ISSUE THREAD

**Issue by elie29** [zendframework/zend-expressive#618]
I have created a new package for dependency injection container using [PHP-DI](http://php-di.org/). You can found [elie29/zend-phpdi-config](https://packagist.org/packages/elie29/zend-phpdi-config). 

The purpose of this package is to offer autowiring technique within PHP-DI by adding autowires key to ConfigProvider. This is very useful so that we don't need to create repeatable Factories unless they are really needed.

**Comment by weierophinney** [comment]
This looks very cool!

Some feedback:

- I'd argue that the `autowires` configuration could be a straight array; any aliases can be created in the `aliases` configuration.
- It would be nice to have the package expose a CLI command for adding an `autowires` entry to configuration.
- It might be nice to provide an abstract factory that can be used to automatically autowire any unknown service.

I'd argue that the first two items should be addressed before we add an option to the Expressive installer. Once they have, open a PR against the zend-expressive-skeleton repository to add it as an option (options are detailed in the `src/ExpressiveInstaller/config.php` file of that repo).

**Comment by elie29** [comment]
Thank you @weierophinney for the feedback.

[php-di-config](https://packagist.org/packages/elie29/zend-phpdi-config) covered now the first two points with valid test and PR created: [PHP-DI Container with autowire configuration](https://github.com/zendframework/zend-expressive-skeleton/pull/255)

**Comment by samsonasik** [comment]
should can be closed in favor of https://github.com/zendframework/zend-expressive-skeleton/pull/255

**Comment by xtreamwayz** [comment]
Merged with zendframework/zend-expressive-skeleton#255
