### ISSUE TITLE
./vendor/bin/expressive Windows 10

### ISSUE THREAD

**Issue by SAMMRUIZ02** [zendframework/zend-expressive#630]
"." it is not recognized as an internal or external command,
program or batch file executable.

I've read that Zend Framework change files zf.php, zf.bat to path where is thrown out php cli. 

Does anyone know what I should do?

When I try to use: 
>composer expressive middleware:create "App\XClacksOverheadMiddleware"  
Output is:
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "expressive" is not defined.

**Comment by froschdesign** [comment]
Same question on [chat](https://zendframework.slack.com/archives/C4QBQUEG5/p1534304282000100), [forum](https://discourse.zendframework.com/t/invoking-the-binary-vendor-bin-expressive-windows-10/698) and issue tracker?! That's a bit too much.
