### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by Auramel** [zendframework/zend-expressive#644]
Hello! I have a problem. My template configuration is:

```
'layout'    => 'layout::main',
        'paths'     => [
            'layout' => [
                ROOT_DIRECTORY . '/templates/layouts',
            ],
            'pages' => [
                ROOT_DIRECTORY . '/templates/pages',
            ],
            'error' => [
                ROOT_DIRECTORY . '/templates/errors',
            ],
        ],
```

In my Handler I writing 
```
return new \Zend\Diactoros\Response\HtmlResponse(
            $this->templateRenderer->render('pages::home::index')
        );
```

And it doesn't working. 
I have structure like this:

> templates/pages/home/index.php

Really it is necessary for each folder to register paths?

**Comment by xtreamwayz** [comment]
Questions should be asked on slack or our forums as you already did: https://discourse.zendframework.com/t/zend-expressive-render-subdirectories/781
