### ISSUE TITLE
Typo in the docbloc

### ISSUE THREAD

**Issue by ncou** [zendframework/zend-expressive#662]
Hi,

Very nice piece of code. I think there is a small typo in the @param values in the MiddlewareFactory class.

https://github.com/zendframework/zend-expressive/blob/master/src/MiddlewareFactory.php#L128

```php
     *
     * @param string|array|**MiddlewarePipe** $middleware
     */
     public function pipeline(...$middleware) : MiddlewarePipe
```

I think it's "MiddlewareInterface" and not "MiddlewarePipe" for the param value. 

If i am right, i can do a PR.

**Comment by dudemelo** [comment]
I think it's correct! MiddlewarePipe is a pipeline/queue of middleware.

[MiddlewarePipe](https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewarePipe.php) `implements` [MiddlewarePipeInterface](https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewarePipeInterface.php) which `extends` [MiddlewareInterface](https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewarePipeInterface.php#L15).

**Comment by ncou** [comment]
yes but the docbloc should say "MiddlewareInterface" because you can also pass some MiddlewareInterface as parameter.

**Comment by dudemelo** [comment]
You're right, I thought it was `@return` instead of `@param`. The `prepare` method is waiting for fifty shades of type but one of those is `MiddlewareInterface`.
https://github.com/zendframework/zend-expressive/blob/87d42944867bd4c7394d4695baed6440fec8207c/src/MiddlewareFactory.php#L63-L67

**Comment by weierophinney** [comment]
@ncou You're correct; please submit a patch.

**Comment by ncou** [comment]
the PR is here https://github.com/zendframework/zend-expressive/pull/663
I have listed all the possible @param value who should be the same as the prepare input params.

Sorry for my poor english.

Keep up the good work.
