### ISSUE TITLE
skeleton project

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive#67]
while this component is in active development, I think we can _start_ have 1 skeleton that people can try and to make sure every feature is working properly.

**Comment by harikt** [comment]
@samsonasik  may be the comments in issue have something https://github.com/zendframework/zend-expressive/issues/37 to do with this issue ?

**Comment by samsonasik** [comment]
oh yes. In my case,  I was trying to do 404 page in middleware pipe (post route) without success, and try access route that didn't registered in allowed methods got 200 status. So, having skeleton help us detect what features that actually working/not.

**Comment by xtreamwayz** [comment]
The 404 page is working. In case you need a skeleton I am working on one that is almost feature complete. Except for Aura.Di and pimple-interop everything seems to work:

https://github.com/xtreamwayz/expressive-composer-installer

**Comment by samsonasik** [comment]
@xtreamwayz yes, the 404 page is working now, but skeleton project is still needed. Yes, I am looking into it. Thanks.

**Comment by RalfEggert** [comment]
Any news on this? Will there be an official `Zend\Expressive` Skeleton Application like the ZendSkeletonApplication for `Zend\Mvc`?

**Comment by Ocramius** [comment]
Looking at this, I don't think a skeleton project is needed. We can provide a `.dist` index file with this project, eventually.

**Comment by weierophinney** [comment]
We're in progress on one, actually: https://github.com/xtreamwayz/expressive-composer-installer

This provides a slim skeleton, but also some composer hooks during initial install/update that prompt for the various adapters you want (router, container, templates — if any, error handler), updates the composer.json, and installs. It also sets up initial configuration based on the choices you make.

So, yes: in progress. I need to do a final review before forking it into the zendframework org, which should happen in the next 10 days.

**Comment by RalfEggert** [comment]
Great news @weierophinney looking into it.

**Comment by stevleibelt** [comment]
@weierophinney looking pretty promising indeed. @all Thanks for the work :+1:

**Comment by weierophinney** [comment]
Please see https://github.com/zendframework/zend-expressive-skeleton

You can now do the following:

```bash
$ composer create-project zendframework/zend-expressive-skeleton
```

This will create a project skeleton, and prompt you for packages to use for routing, templating, service container, and error handler.
