### ISSUE TITLE
Injecting container into middleware?

### ISSUE THREAD

**Issue by moderndeveloperllc** [zendframework/zend-expressive#77]
There are many types of services that may be useful to have in multiple middleware classes - database connectivity for instance. If I am using a Configuration-Driven Container, it would appear that I would want to make my middleware classes `factories` instead of `invokables` so I could inject the container on `__construct()` and have the standard `public function __invoke($req, $res, $next)` for when the middleware gets piped.

Am I just eating the penalty for non lazy-loading because I want the container to be available? Or am I thinking about this in the wrong way?

**Comment by codeliner** [comment]
@moderndeveloperllc You mix the concepts a bit :smile: 
A middleware should not be its own `factory`. What you can and should do is register a `middleware factory` as a service in your container.
Then follow the docs to let zend-expressive lazy-load your middleware: 
- https://github.com/zendframework/zend-expressive/blob/master/doc/book/usage-examples.md#using-the-container-to-register-middleware
- https://github.com/zendframework/zend-expressive/blob/master/doc/book/usage-examples.md#lazy-loaded-middleware

See the lazy-load example. `middleware` is a `service name` in the example and used to get the `invokeable middleware` from the container. When your factory is registered with such a `service name` it gets the container injected when it is invoked. 
See the [Factory-Driven Creation of a router](https://github.com/zendframework/zend-expressive/blob/master/doc/book/router.aura.md#factory-driven-creation) for example (a router is a middleware). Same works for any other middleware. Your factory can get further dependencies from the container and create the `invokable middleware`.

**Comment by moderndeveloperllc** [comment]
@codeliner Yeah - my bad. Never ask a question right before bed! I meant to say have a factory for the middleware in the `factories` service config, instead of the middleware class as a line in `invokables`. Thanks for pointing out the example I missed. I would have use a `__construct()` instead of `__invoke()` on the factory class.
